"use client";
import { useState } from "react";
import type { WeeklyPortrait } from "@/lib/analysis/weeks";
import { weight } from "./shared";
const pct=(n:number|null|undefined)=>n==null?"—":`${(n*100).toFixed(1)}%`;
const days=["周一","周二","周三","周四","周五","周六","周日"];
export function DishPortrait({report,day,dishId,onChange}:{report:WeeklyPortrait;day:string|null;dishId:string;onChange:(id:string)=>void}) {
 const frame=day?report.daily.find(d=>d.date===day):report.current;
 const dish=frame?.dishInsights.find(d=>d.dishId===dishId);
 const periods=day?report.daily.find(d=>d.date===day)?.periods:report.periods;
 const daily=report.daily.map(d=>({date:d.date,future:d.future,...d.dishInsights.find(v=>v.dishId===dishId)}));
 const max=Math.max(.01,...daily.map(d=>d.share??0));
 const weekChange=report.comparisons[2]?.changes.find(d=>d.dishId===dishId);
 const dayChange=day?report.daily.find(d=>d.date===day)?.dailyChange.changes.find(d=>d.dishId===dishId):null;
 return <section className="scale-panel single-dish"><div className="scale-section-heading"><div><h2>每道菜的独立画像</h2><p className="scale-muted">全部菜品均可选择，同一类别的菜也分别分析</p></div><label className="dish-picker">查看菜品<select value={dishId} onChange={e=>onChange(e.target.value)}>{report.current.dishInsights.map(d=><option key={d.dishId} value={d.dishId}>{d.name}（{d.dishId}）</option>)}</select></label></div>
 {dish?<><div className="single-dish-heading"><div><span>{day??`${report.weekStart} — ${report.weekEnd}`}</span><h3>{dish.name}</h3><small>菜品编号：{dish.dishId}</small></div><strong>{pct(dish.share)}<small>有效取用重量占比</small></strong><span className="portrait-chip">{dish.status}</span></div><p className="dish-conclusion">{dish.conclusion}</p><p className="dish-advice">建议：{dish.suggestion}</p><div className="dish-sample-stats"><span>{dish.samples}/{dish.expectedDays} 天有效样本</span><span>{dish.stockoutDays} 天有缺菜</span><span>有效取用 {weight(dish.grams)}</span><span>全部已观测 {weight(dish.observedTakeG)}</span></div>
 <div className="dish-detail-grid"><div><h3>这道菜每天的变化</h3><div className="dish-day-bars" role="img" aria-label={`${dish.name}每日有效取用重量占比`}>{daily.map((d,i)=><div key={d.date}><span>{d.future?"未到":pct(d.share)}</span><div className="dish-day-track">{d.share==null?<i className="dish-day-unknown"/>:<i style={{height:`${d.share/max*100}%`}}/>}</div><small>{days[i]}</small><small>{d.samples??0}天有效</small></div>)}</div><p className="scale-muted">各日分母为当日全部菜品的有效取用重量；无有效记录留空。</p>{day&&<p className="dish-delta">较前一天（共同菜品口径）：{dayChange?`${dayChange.deltaPoints>=0?"+":""}${dayChange.deltaPoints.toFixed(1)}个百分点`:"暂无可比数据"}</p>}</div>
 <div><h3>这道菜在哪些时段被取用？</h3><table className="dish-period-table"><thead><tr><th>时段</th><th>重量占比</th><th>取用量</th><th>记录天数</th></tr></thead><tbody>{periods?.map(m=>{const row=m.dishes.find(d=>d.dishId===dishId);return <tr key={m.id}><td>{m.name}<small>{m.hours}</small></td><td>{pct(row?.share)}</td><td>{weight(row?.grams)}</td><td>{row?.days??"—"}</td></tr>;})}</tbody></table><p className="scale-muted">各时段分母为该时段所有菜的已观测取用重量；没有分钟记录时不从日统计推算。</p></div></div>
 <div className="dish-week-strip">{report.fourWeeks.map((w,i)=>{const row=w.dishInsights.find(d=>d.dishId===dishId);return <div key={w.start}><small>第{i+1}周 · {w.start.slice(5)}—{w.end.slice(5)}</small><strong>{pct(row?.share)}</strong><span>{row?.samples??0}天有效 · {row?.status??"暂无记录"}</span></div>;})}</div><p className="dish-delta">较前周（同星期、共同菜品口径）：{weekChange?.deltaPoints!=null?`${weekChange.deltaPoints>=0?"+":""}${weekChange.deltaPoints.toFixed(1)}个百分点，${weekChange.pairedDays}个配对日期`:`${weekChange?.pairedDays??0}个配对日期，未达到可比条件`}</p>
 </>:<p className="scale-muted">暂无菜品目录，可在数据接入后查看独立画像。</p>}
 </section>;
}
export function DishFourWeeks({report,dishId,onChange}:{report:WeeklyPortrait;dishId:string;onChange:(id:string)=>void}) {
 return <div className="scale-table-scroll dish-week-table"><table className="scale-plan-table"><thead><tr><th>菜品（点击查看独立画像）</th>{report.fourWeeks.map((w,i)=><th key={w.start}>第{i+1}周<small>{w.start.slice(5)}—{w.end.slice(5)}</small></th>)}<th>第4周较第3周</th></tr></thead><tbody>{report.current.dishInsights.map(d=>{const change=report.comparisons[2]?.changes.find(c=>c.dishId===d.dishId);return <tr key={d.dishId} className={dishId===d.dishId?"dish-row-selected":""}><td><button onClick={()=>onChange(d.dishId)} aria-pressed={dishId===d.dishId}>{d.name}<small>{d.dishId}</small></button></td>{report.fourWeeks.map(w=>{const entry=w.distribution.find(c=>c.dishId===d.dishId);return <td key={w.start}><strong>{pct(entry?.share)}</strong><div className="dish-cell-bar"><i style={{width:`${(entry?.share??0)*100}%`}}/></div><small>{entry?.samples??0}天有效</small></td>;})}<td>{change?.deltaPoints!=null?`${change.deltaPoints>=0?"+":""}${change.deltaPoints.toFixed(1)}个百分点`:"不可比较"}<small>{change?.pairedDays??0}个配对日期</small></td></tr>;})}</tbody></table></div>;
}

export function DishOverview({report,day,dishId,onChange}:{report:WeeklyPortrait;day:string|null;dishId:string;onChange:(id:string)=>void}) {
 const [view,setView]=useState<"daily"|"periods">("daily");
 const frame=day?report.daily.find(d=>d.date===day)!:report.current;
 const periods=day?report.daily.find(d=>d.date===day)!.periods:report.periods;
 const dailyMaps=report.daily.map(d=>new Map(d.dishInsights.map(v=>[v.dishId,v])));
 const periodMaps=periods.map(p=>new Map(p.dishes.map(v=>[v.dishId,v])));
 return <section className="scale-panel all-dish-overview"><div className="scale-section-heading"><div><h2>全部菜品画像</h2><p className="scale-muted">共 {frame.dishInsights.length} 道菜 · 每行一道菜，保留无记录的菜品 · 点击菜名查看详情</p></div><div className="dish-view-switch" aria-label="表格展示方式"><button aria-pressed={view==="daily"} onClick={()=>setView("daily")}>每日对照</button><button aria-pressed={view==="periods"} onClick={()=>setView("periods")}>各时段对照</button></div></div>
 {view==="periods"&&report.periodError&&<p role="alert">{report.periodError}</p>}
 <p className="scale-muted">{view==="daily"?"每日占比以当日全部有效取用重量为分母；整周占比按重量汇总，不是每日百分比的平均。":"时段占比以该时段全部已观测取用重量为分母，包含供应受限观测，与有效样本口径不同。"} — 表示无法计算，0.0% 表示有可计算的记录但占比为零或不足0.05%。</p>
 <div className="dish-matrix-scroll" role="region" aria-label="全部菜品占比对照表，可横向和纵向滚动" tabIndex={0}><table className="dish-matrix"><caption>{view==="daily"?`${report.weekStart} 至 ${report.weekEnd} 每道菜的每日占比`:`${day??report.weekStart+" 至 "+report.weekEnd} 每道菜的时段占比`}</caption><thead><tr><th scope="col">菜品</th><th scope="col">{day?"当日":"整周"}有效占比</th>{view==="daily"?report.daily.map((d,i)=><th scope="col" key={d.date} className={day===d.date?"dish-column-active":""}>{days[i]}<small>{d.date.slice(5)}{d.future?" · 未到":d.inProgress?" · 未完结":""}</small></th>):periods.map(p=><th scope="col" key={p.id}>{p.name}<small>{p.hours}</small></th>)}<th scope="col">{day?"当日":"整周"}分析与建议</th></tr></thead><tbody>{frame.dishInsights.map(d=><tr key={d.dishId} className={dishId===d.dishId?"dish-row-selected":""}><th scope="row"><button className="dish-name-link" aria-pressed={dishId===d.dishId} onClick={()=>onChange(d.dishId)}>{d.name}</button><small>{d.dishId}</small></th><td><strong>{pct(d.share)}</strong><small>{d.samples}/{d.expectedDays} 天有效</small></td>{view==="daily"?report.daily.map((date,i)=>{const entry=dailyMaps[i].get(d.dishId);return <td key={date.date} className={day===date.date?"dish-column-active":""}><span>{date.future?"未到":pct(entry?.share)}</span><div className="dish-cell-bar"><i style={{width:`${(entry?.share??0)*100}%`}}/></div></td>;}):periods.map((period,i)=>{const entry=periodMaps[i].get(d.dishId);return <td key={period.id}><span>{pct(entry?.share)}</span><div className="dish-cell-bar"><i style={{width:`${(entry?.share??0)*100}%`}}/></div><small>{entry?`${entry.days}天记录 · ${weight(entry.grams)}`:"暂无分钟记录"}</small></td>;})}<td className="dish-row-analysis"><strong>{d.status}</strong><details><summary>查看这道菜的依据与建议</summary><p>{d.conclusion}</p><p>建议：{d.suggestion}</p></details></td></tr>)}</tbody></table>{!frame.dishInsights.length&&<p className="scale-muted">暂无菜品目录，接入数据后展示。</p>}</div>
 </section>;
}
