"use client";
import { useSupplyFeedback,SupplyHint,DishSupplyAdvice } from "./freshness-advice";
import { Fragment,useState } from 'react';
import { ArrowLeft,RefreshCw } from 'lucide-react';
import type { CurrentProfile } from '@/lib/analysis/current-profile';
import type { AnalysisResult } from '@/lib/analysis/contract';
import { portraitFingerprint,tileWeights,type PortraitCache } from '@/lib/analysis/view-model';
import { usePolling,Notice,weight,dateToday } from './shared';
import { pct } from './portrait-visuals';
import AnalysisAssistant from './analysis-assistant';
import ModelConnection from './model-connection';
const weekdays=['周一','周二','周三','周四','周五','周六','周日'];
const colors=['#286953','#438368','#628d6b','#95784c','#aa815a','#537f83'];
export default function OverallPortrait({cache,connectionVersion,onConnectionChanged,onBack}:{cache:PortraitCache<AnalysisResult>;connectionVersion:number;onConnectionChanged:()=>void;onBack:()=>void}){
 const feedback=useSupplyFeedback();
 const query=usePolling<CurrentProfile>('/api/intelligence/portrait?scope=overall',60000),r=query.data;
 const [weekday,setWeekday]=useState<number|null>(null),[period,setPeriod]=useState<number|null>(null),[search,setSearch]=useState(''),[expanded,setExpanded]=useState(''),[focus,setFocus]=useState('');
 const distribution=r?(period!=null?r.periods[period].dishes.map(d=>({dishId:d.dishId,name:d.name,grams:d.grams,share:d.share,samples:d.days})):r.dishes.map(d=>({dishId:d.dishId,name:d.name,grams:weekday==null?d.currentShare:d.weekdays[weekday].estimateG,share:weekday==null?d.currentShare:d.weekdays[weekday].share,samples:weekday==null?d.samples:d.weekdays[weekday].samples}))):[];
 const tiles=tileWeights(distribution.map(d=>({dishId:d.dishId,grams:d.grams??0})),0,0,100,60),active=distribution.find(d=>d.dishId===focus);
 function reveal(id:string){setSearch('');setExpanded(id);setFocus(id);setTimeout(()=>document.getElementById(`overall-dish-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),0);}
 return <section className="intelligence portrait-dashboard"><div className="scale-page-title"><div><span className="scale-eyebrow">主画像 · 随新数据更新的模型估计</span><h1>当前客群画像</h1><p className="scale-muted">融合长期基础、近期变化与有效当日观测，估计当前客群的取用倾向。</p></div><button className="scale-button" onClick={query.refresh}><RefreshCw size={15}/>刷新模型</button></div><button className="portrait-back" onClick={onBack}><ArrowLeft size={16}/>查看历史周／日画像</button>
 {query.error&&<Notice error>{query.error}</Notice>}{query.loading&&<Notice>正在根据全部可用历史计算整体画像…</Notice>}
 {r&&<><section className="scale-panel"><div className="scale-section-heading"><div><h2>{period!=null?`${r.periods[period].name} · 已观测时段倾向`:weekday==null?'当前取用倾向 · 模型估计':`${weekdays[weekday]} · 模型估计取用构成`}</h2><p className="scale-muted">{period!=null?'实际分钟记录的重量构成，与全天模型历史范围和分母不同。':'面积表示达到建模条件的菜品之间的估计重量占比，不是人数比例或喜爱评分。'}</p></div></div>
 <div className="portrait-date-tabs overall-weekdays"><button aria-pressed={weekday==null&&period==null} onClick={()=>{setWeekday(null);setPeriod(null);}}>当前</button>{weekdays.map((name,i)=><button key={name} aria-pressed={weekday===i&&period==null} onClick={()=>{setWeekday(i);setPeriod(null);}}>{name}</button>)}</div>
 <div className="portrait-search"><label>定位菜品 <input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索菜名或编号"/></label>{search&&<div className="portrait-search-results">{r.dishes.filter(d=>`${d.name} ${d.dishId}`.toLowerCase().includes(search.toLowerCase())).map(d=><button key={d.dishId} onClick={()=>reveal(d.dishId)}>{d.name} · {d.dishId}</button>)}</div>}</div>
 <div className="dish-treemap" aria-label="当前客群模型估计分布">{tiles.map((t,i)=>{const d=distribution.find(v=>v.dishId===t.dishId)!;return <button key={t.dishId} className={focus===t.dishId?'focused':''} style={{left:`${t.x}%`,top:`${t.y/60*100}%`,width:`${t.width}%`,height:`${t.height/60*100}%`,background:colors[i%colors.length]}} title={`${d.name}（${d.dishId}） ${pct(d.share)}${period==null&&weekday==null?'':` · ${weight(d.grams)}`}`}  aria-label={`${d.name} ${d.dishId} ${pct(d.share)} 查看模型依据`} onMouseEnter={()=>setFocus(t.dishId)} onFocus={()=>setFocus(t.dishId)} onClick={()=>reveal(t.dishId)}>{t.width>9&&t.height>6&&<><span>{d.name}</span><strong>{pct(d.share)}</strong></>}</button>;})}{!tiles.length&&<p className="treemap-empty">{period!=null?(r.periods[period].totalG===null?'暂无分钟取用记录，不能推算分布。':'该时段已观测取用为零，无法计算占比。'):r.modeledCount===0?'尚无菜品达到21个有效日期，模型学习中。':'已建模菜品的日均取用合计为零，无法计算占比。'}</p>}</div>
 <p className="tree-selection">{active?`${active.name}（${active.dishId}） · ${pct(active.share)}${period==null&&weekday==null?'':` · ${period==null?'估计日均':'已观测'} ${weight(active.grams)}`} · ${active.samples}个日期样本`:'悬停查看估计值，点击菜品查看模型依据。'}</p>
 {period==null&&weekday!=null&&<p className="scale-muted">星期样本少时向基础日均量收缩；该星期没有样本时仅沿用基础估计，不代表发现了星期规律。</p>}
 <details><summary>学习中、零取用或时段无记录的菜品</summary><div className="portrait-search-results">{r.dishes.filter(d=>!(distribution.find(v=>v.dishId===d.dishId)?.grams??0)).map(d=><button key={d.dishId} onClick={()=>reveal(d.dishId)}>{d.name} · {period==null?d.status:distribution.some(v=>v.dishId===d.dishId)?'已观测零取用':'暂无时段记录'}</button>)}</div></details><details><summary>模型口径与限制</summary><p>{r.method}</p>{r.limitations.map(v=><p key={v}>{v}</p>)}<p>版本：{r.version} · 历史28天权重减半 · 星期收缩7个加权日期</p></details></section>
 <section className="scale-panel"><h2>时段规律 · 已观测倾向</h2><p className="scale-muted">查询范围 {r.periodWindow.startDate} — {r.periodWindow.endDate}；实际记录 {r.periodObservedStart??'暂无'} — {r.periodObservedEnd??'暂无'}。点击时段查看全部菜品构成，不由全天模型推算时段需求。</p>{r.periodWindow.error&&<Notice error>{r.periodWindow.error}</Notice>}<div className="rhythm-chart">{r.periods.map(p=><button key={p.id} aria-pressed={period===p.id} onClick={()=>setPeriod(p.id)}><span>{weight(p.totalG)}</span><div><i style={{height:`${(p.totalG??0)/Math.max(1,...r.periods.map(v=>v.totalG??0))*100}%`}}/></div><strong>{p.name}</strong><small>{p.hours}</small></button>)}</div></section>
 <section className="scale-panel"><AnalysisAssistant key={`${connectionVersion}:${portraitFingerprint(r)}`} mode="overall" startDate={r.startDate??dateToday()} endDate={r.endDate??dateToday()} cache={cache} fingerprint={portraitFingerprint(r)} connectionVersion={connectionVersion} hasData={r.modeledCount>0||r.periods.some(p=>p.totalG!=null)}/></section>
 <section className="scale-panel unified-dishes"><h2>全部菜品 · 模型明细</h2><p className="scale-muted">近期基准日均量不是明日备料预测，当前占比还结合星期及符合条件的当天观测。搜索与上方定位框联动，点击菜名展开星期、时段依据与建议。</p><div className="scale-table-scroll"><table className="scale-plan-table"><thead><tr><th>菜品</th><th>近期基准日均量</th><th>当前估计占比</th><th>相对长期构成</th><th>有效日期／已有日期</th><th>学习状态</th></tr></thead><tbody>{r.dishes.filter(d=>`${d.name} ${d.dishId}`.toLowerCase().includes(search.toLowerCase())).map(d=><Fragment key={d.dishId}><tr id={`overall-dish-${d.dishId}`} className={expanded===d.dishId?'dish-row-selected':''}><td><button className="dish-name-link" aria-expanded={expanded===d.dishId} onClick={()=>setExpanded(expanded===d.dishId?'':d.dishId)}>{d.name}</button><SupplyHint dishId={d.dishId} query={feedback}/><small>{d.dishId}</small></td><td>{weight(d.estimateG)}</td><td>{pct(d.currentShare)}</td><td>{d.changePoints==null?'—':`${d.changePoints>=0?'+':''}${d.changePoints.toFixed(1)}个百分点`}</td><td>{d.samples}／{d.knownDays}</td><td>{d.status}</td></tr>{expanded===d.dishId&&<tr><td colSpan={6}><div className="dish-inline-detail"><p>有效样本 {d.firstValidDate??'暂无'} — {d.lastValidDate??'暂无'}。{d.estimateG==null?`还需至少${21-d.samples}个有效日期；不将无模型值当零。`:'历史按28天半衰期加权，再计算星期估计；仅在覆盖和供应合格时融合当天取用构成。'}</p><h3>星期估计</h3><div className="inline-data-strip">{d.weekdays.map(w=><div key={w.weekday}><span>{weekdays[w.weekday]}</span><strong>{weight(w.estimateG)}</strong><small>{pct(w.share)} · {w.samples}个星期样本</small></div>)}</div><h3>时段观测</h3><div className="inline-data-strip">{r.periods.map(p=>{const row=p.dishes.find(v=>v.dishId===d.dishId);return <div key={p.id}><span>{p.name}</span><strong>{pct(row?.share)}</strong><small>{weight(row?.grams)} · {row?.days??0}天记录</small></div>;})}</div><p>建议：{d.estimateG==null?'继续收集完整且供应充足的营业日记录。':'结合当前供应、近期变化和独立备料预测确定试供量，不能直接用长期日均量下达备料计划。'}</p><DishSupplyAdvice dishId={d.dishId} query={feedback}/></div></td></tr>}</Fragment>)}</tbody></table></div></section></>}
 <ModelConnection onChanged={onConnectionChanged}/></section>;
}
