"use client";
import { Fragment,useEffect,useState } from 'react';
import type { WeeklyPortrait } from '@/lib/analysis/weeks';
import { useSupplyFeedback,SupplyHint,DishSupplyAdvice } from './freshness-advice';

import { weight } from './shared';
import { pct } from './portrait-visuals';
export default function PortraitDetails({report,day,selected}:{report:WeeklyPortrait;day:string|null;selected:{id:string;nonce:number}|null}) {
 const feedback=useSupplyFeedback(day??report.weekStart,day??(report.weekEnd>report.asOf.slice(0,10)?report.asOf.slice(0,10):report.weekEnd));
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState(''),[previousSelection,setPreviousSelection]=useState(selected);
 if(selected!==previousSelection){setPreviousSelection(selected);if(selected){setSearch('');setExpanded(selected.id);}}
 const frame=day?report.daily.find(d=>d.date===day)!:report.current;
 const periods=day?report.daily.find(d=>d.date===day)!.periods:report.periods;
 const changes=day?report.daily.find(d=>d.date===day)!.dailyChange.changes:report.comparisons[2].changes;
 useEffect(()=>{if(selected){const t=setTimeout(()=>document.getElementById(`dish-row-${selected.id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),0);return()=>clearTimeout(t);}},[selected]);
 return <section className="scale-panel unified-dishes"><div className="scale-section-heading"><div><h2>全部菜品明细</h2><p className="scale-muted">{frame.dishInsights.length}道菜 · 展开一行查看每日、时段、四周数据及建议</p></div><input aria-label="搜索明细菜名或编号" type="search" placeholder="搜索菜名或编号" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="scale-table-scroll"><table className="scale-plan-table"><thead><tr><th>菜品</th><th>已观测取用</th><th>有效重量占比</th><th>有效样本</th><th>{day?'较前日':'较前周'}</th><th>分析摘要</th></tr></thead><tbody>{frame.dishInsights.filter(d=>`${d.name} ${d.dishId}`.toLowerCase().includes(search.toLowerCase())).map(d=>{const change=changes.find(c=>c.dishId===d.dishId)?.deltaPoints;return <Fragment key={d.dishId}><tr id={`dish-row-${d.dishId}`} className={expanded===d.dishId?'dish-row-selected':''}><td><button className="dish-name-link" aria-expanded={expanded===d.dishId} onClick={()=>setExpanded(expanded===d.dishId?'':d.dishId)}>{d.name}</button><SupplyHint dishId={d.dishId} query={feedback}/><small>{d.dishId}</small></td><td>{weight(d.observedTakeG)}</td><td>{pct(d.share)}</td><td>{d.samples}/{d.expectedDays}天</td><td>{change==null?'不可比较':`${change>=0?'+':''}${change.toFixed(1)}个百分点`}</td><td>{d.status}</td></tr>{expanded===d.dishId&&<tr><td colSpan={6}><div className="dish-inline-detail"><p>{d.conclusion}</p><p>建议：{d.suggestion}</p><DishSupplyAdvice dishId={d.dishId} query={feedback} historical/><p>有效取用 {weight(d.grams)} · 缺菜 {d.stockoutDays} 天。已观测取用含供应受限记录，有效占比仅使用完整且供应充足的样本。</p><h3>本周每天 · 有效重量占比</h3><div className="inline-data-strip">{report.daily.map(v=><div key={v.date}><span>{v.date.slice(5)}{v.inProgress?'（未完结）':''}</span><strong>{v.future?'未到':pct(v.dishInsights.find(x=>x.dishId===d.dishId)?.share)}</strong></div>)}</div><h3>{day?'当日':'整周'}各时段 · 已观测重量占比</h3><div className="inline-data-strip">{periods.map(v=>{const r=v.dishes.find(x=>x.dishId===d.dishId);return <div key={v.id}><span>{v.name}</span><strong>{pct(r?.share)}</strong><small>{weight(r?.grams)} · {r?.days??0}天记录</small></div>;})}</div><h3>连续四周 · 各周有效重量占比</h3><div className="inline-data-strip">{report.fourWeeks.map(v=><div key={v.start}><span>{v.start}—{v.end}</span><strong>{pct(v.dishInsights.find(x=>x.dishId===d.dishId)?.share)}</strong></div>)}</div><p>周际变化按共同星期与共同菜品重新计算，分母与各周展示占比可能不同。— 表示无法计算，不代表零。</p></div></td></tr>}</Fragment>;})}</tbody></table></div></section>;
}
