"use client";
import { useCallback, useEffect, useRef, useState } from "react";

export function weight(value: number | null | undefined) { if(value == null || !Number.isFinite(value)) return "—"; return value >= 1000 ? `${(value / 1000).toLocaleString("zh-CN", { maximumFractionDigits: 2 })} kg` : `${Math.round(value).toLocaleString("zh-CN")} g`; }
export function dateToday() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
export function nextDate(date: string) { return new Date(Date.parse(`${date}T00:00:00Z`) + 86400000).toISOString().slice(0,10); }
export function clockTime(at: string | null | undefined) { return at ? new Date(at).toLocaleTimeString("zh-CN", { hour:"2-digit", minute:"2-digit", second:"2-digit", timeZone:"Asia/Shanghai" }) : "—"; }
export async function request<T>(url: string, payload?: unknown): Promise<T> { const response = await fetch(url, payload === undefined ? { cache:"no-store" } : { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) }); const result = await response.json() as T & {error?:string;message?:string}; if(!response.ok) throw new Error(result.error || result.message || "暂时无法连接，请重试"); return result as T; }
export function usePolling<T>(url: string | null, interval: number) {
 const [state,setState] = useState<{key:string;data?:T;error?:string}>({key:""});
 const refreshRef=useRef<()=>void>(()=>{});
 useEffect(()=> { if(!url) return; let disposed=false, busy=false; const controllers=new Set<AbortController>();
  async function refresh() { if(busy || disposed) return; busy=true;const controller=new AbortController();controllers.add(controller);try { const response=await fetch(url!,{cache:"no-store",signal:controller.signal});const data=await response.json() as T & {error?:string};if(!response.ok){if(response.status===503 && data.error?.includes("维护")){if(!disposed)setState({key:url!,error:data.error});return;}throw new Error(data.error || "暂时无法连接");}if(!disposed)setState({key:url!,data}); } catch(error) { if(!disposed)setState(previous=>({key:url!,data:previous.key===url?previous.data:undefined,error:error instanceof Error?error.message:"连接中断"})); } finally {controllers.delete(controller);busy=false;} }
  refreshRef.current=()=>void refresh();void refresh(); const timer=setInterval(()=>void refresh(),interval);return()=>{disposed=true;clearInterval(timer);controllers.forEach(c=>c.abort());};
 },[url,interval]);
 const refresh=useCallback(()=>refreshRef.current(),[]);
 return {data:state.key===url?state.data:undefined,error:state.key===url?state.error:undefined,loading:state.key!==url,refresh};
}
export function Sparkline({values,label,large=false}:{values:(number|null)[];label:string;large?:boolean}) { const width=240,height=large?88:48,max=Math.max(1,...values.filter((v):v is number=>v!=null));const points=values.map((v,i)=>v==null?null:`${values.length>1?i/(values.length-1)*width:width/2},${height-5-Math.max(0,v)/max*(height-10)}`);const segments:string[]=[];let current:string[]=[];points.forEach(point=>{if(point==null){if(current.length)segments.push(current.join(" "));current=[];}else current.push(point);});if(current.length)segments.push(current.join(" "));return <svg className="scale-sparkline" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}><path d={`M0 ${height-4}H${width}`} className="spark-baseline"/>{segments.map((segment,i)=><polyline key={i} points={segment} fill="none" vectorEffect="non-scaling-stroke"/>)}{points.filter((point):point is string=>point!=null).length===1&&<circle cx={Number(points.find(Boolean)?.split(",")[0])} cy={Number(points.find(Boolean)?.split(",")[1])} r="3"/>}</svg>; }
export function Notice({children,error=false}:{children:React.ReactNode;error?:boolean}) { return <p className={`scale-notice ${error?"is-error":""}`} role={error?"alert":"status"}>{children}</p>; }
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.focus();function onKey(event:KeyboardEvent){if(event.key==="Escape")onClose();if(event.key==="Tab"){const elements=ref.current?.querySelectorAll<HTMLElement>('button, input, select, textarea, a[href]');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("keydown",onKey);previous?.focus();};},[onClose]);return <div className="scale-modal-backdrop" onClick={event=>{if(event.target===event.currentTarget)onClose();}}><div className="scale-modal" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="scale-icon-button" onClick={onClose} aria-label="关闭">×</button></header>{children}</div></div>;}
