import { env } from "cloudflare:workers";
import { modelConfig,type ModelConfig } from "./provider.ts";
import { encryptModelKey,decryptModelKey } from "./key-crypto.ts";
const id="intelligence-v1";
interface Row {ciphertext:string|null;suffix:string|null;disabled:number;updated_at:string;}
async function stored(){if(!env.DB)throw new Error("数据库未连接");return env.DB.prepare("SELECT ciphertext,suffix,disabled,updated_at FROM model_credentials WHERE id=?").bind(id).first<Row>();}
export async function resolveModelConfig():Promise<ModelConfig>{const row=await stored();if(!row)return modelConfig(env);if(row.disabled||!row.ciphertext)return {apiKey:"",baseUrl:"https://api.deepseek.com",model:"deepseek-flash"};const saved=JSON.parse(await decryptModelKey(row.ciphertext,env.ANALYSIS_KEY_SECRET??"")) as {apiKey:string;model:string};return {...saved,baseUrl:"https://api.deepseek.com"};}
export async function credentialStatus(){const row=await stored();if(row?.ciphertext&&!row.disabled){const config=await resolveModelConfig();return {configured:true,model:config.model,suffix:row.suffix,source:"saved",message:"已连接 DeepSeek（上次保存时验证通过）"};}const config=await resolveModelConfig();return {configured:!!config.apiKey,model:config.model,suffix:config.apiKey?config.apiKey.slice(-4):null,source:row?.disabled?"disabled":"environment",message:config.apiKey?"已读取服务端配置，可测试连接":"在下方填写 DeepSeek API Key 即可连接"};}
export async function saveModelKey(apiKey:string,model:string){if(!env.DB)throw new Error("数据库未连接");const cipher=await encryptModelKey(JSON.stringify({apiKey,model}),env.ANALYSIS_KEY_SECRET??"");await env.DB.prepare("INSERT INTO model_credentials(id,ciphertext,suffix,disabled,updated_at) VALUES (?,?,?,0,?) ON CONFLICT(id) DO UPDATE SET ciphertext=excluded.ciphertext,suffix=excluded.suffix,disabled=0,updated_at=excluded.updated_at").bind(id,cipher,apiKey.slice(-4),new Date().toISOString()).run();}
export async function disconnectModel(){if(!env.DB)throw new Error("数据库未连接");await env.DB.prepare("INSERT INTO model_credentials(id,ciphertext,suffix,disabled,updated_at) VALUES (?,NULL,NULL,1,?) ON CONFLICT(id) DO UPDATE SET ciphertext=NULL,suffix=NULL,disabled=1,updated_at=excluded.updated_at").bind(id,new Date().toISOString()).run();}
export async function testDeepSeek(config:ModelConfig,signal:AbortSignal){if(!config.apiKey)throw new Error("请先填写 API Key");let response:Response;try{response=await fetch(`${config.baseUrl}/chat/completions`,{method:"POST",redirect:"manual",signal,headers:{Authorization:`Bearer ${config.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:config.model,messages:[{role:"user",content:"Reply OK."}],max_tokens:16,stream:false,...(new URL(config.baseUrl).hostname==="api.deepseek.com"?{thinking:{type:"disabled"}}:{})})});}catch{throw new Error(signal.aborted?"连接测试超时，请重试":"无法连接模型服务，请检查网络");}if(response.status>=300&&response.status<400)throw new Error("模型服务返回重定向，已停止请求，请检查服务地址");if(!response.ok)throw new Error(response.status===401||response.status===403?"API Key 无效或没有权限":response.status===429?"服务限流或账户额度不足":`连接失败（HTTP ${response.status}），请检查模型与账户状态`);let result:{choices?:{message?:{content?:string}}[]};try{result=await response.json() as typeof result;}catch{throw new Error("模型未返回有效测试响应");}if(!result.choices?.[0]?.message?.content)throw new Error("模型未返回有效测试响应");}
