import { hasActiveFreshness } from "../freshness/repository.ts";
import { env } from "cloudflare:workers";
import type { DailySummary, DishRealtime, MinuteBucket, Realtime, Sample, ScaleConfig, ScaleView, Source, WeightEvent } from "./types.ts";
import { consumptionRate, dishEmptySeconds, measure, newState, updateBuckets, type DeviceState } from "./engine.ts";
import { menuDishFilter } from "./menu.ts";
function db() { if (!env.DB) throw new Error("数据库未连接"); return env.DB; }
type Latest = { revision: number; payload: string };
export const localDate = (at: string) => new Date(Date.parse(at) + 8 * 3600000).toISOString().slice(0, 10);
export async function readConfigs(source: Source): Promise<ScaleConfig[]> { const rows = await db().prepare("SELECT payload FROM scale_configs WHERE source=? ORDER BY id").bind(source).all<{ payload: string }>(); return rows.results.map(r => JSON.parse(r.payload) as ScaleConfig).sort((a,b)=>(a.position??10001)-(b.position??10001)||a.id.localeCompare(b.id,undefined,{numeric:true})); }
export async function readSettings(source: Source): Promise<{ openTime: string; closeTime: string }> { const row = await db().prepare("SELECT payload FROM scale_settings WHERE source=?").bind(source).first<{ payload: string }>(); return row ? JSON.parse(row.payload) : { openTime: "11:00", closeTime: "22:00" }; }
export async function saveSettings(source: Source, settings: { openTime: string; closeTime: string }) { if (settings.openTime >= settings.closeTime) throw new Error("营业结束时间必须晚于开始时间"); await db().prepare("INSERT INTO scale_settings(source,payload) VALUES (?,?) ON CONFLICT(source) DO UPDATE SET payload=excluded.payload").bind(source, JSON.stringify(settings)).run(); return settings; }
export async function saveConfig(source: Source, input: Omit<ScaleConfig, "updatedAt"> & { updatedAt?: string }) {
  const existing = (await readConfigs(source)).find(c => c.id === input.id), config = { ...input, updatedAt: new Date().toISOString() };
  const reset = existing && ["dishId", "tareG", "fullG", "noiseG", "enabled"].some(key => existing[key as keyof ScaleConfig] !== config[key as keyof ScaleConfig]);
  if(reset && await hasActiveFreshness(config.id)) throw new Error("该碗位正在进行时限管理，请先撤下并结束当前批次，再修改绑定或校准");
  for (let attempt = 0; attempt < 5; attempt++) {
    const before = await latest(source, config.id), operation = crypto.randomUUID(), state = structuredClone(before.state);
    if (reset) { state.stableNet = null; state.displayedNet = null; state.candidates = []; state.needsBaseline = true; state.beforeRemoval = null; state.mode = "unstable"; state.suppressOpening = existing?.dishId === config.dishId && !!state.openedDate; if (existing?.dishId !== config.dishId) delete state.openedDate; }
    const condition = gate(source, config.id, operation), at = new Date().toISOString(), calibrationEvent: WeightEvent | null = reset && before.state.stableNet !== null && before.state.sampledAt && localDate(before.state.sampledAt) === localDate(at) ? { id: `${source}:calibration:${operation}`, source, scaleId: config.id, dishId: existing!.dishId, at, receivedAt: at, kind: "correction", weightG: 0, resolution: "calibration" } : null, statements = [
      db().prepare(`INSERT INTO scale_latest(source,scale_id,revision,operation_id,payload) VALUES (?,?,1,?,?) ON CONFLICT(source,scale_id) DO UPDATE SET revision=scale_latest.revision+1,operation_id=excluded.operation_id,payload=excluded.payload WHERE scale_latest.revision=?${reset ? " AND NOT EXISTS(SELECT 1 FROM freshness_batches WHERE scale_id=? AND status='active')" : ""}`).bind(source, config.id, operation, JSON.stringify(state), before.revision,...(reset?[config.id]:[])),
      db().prepare(`INSERT INTO scale_configs(source,id,payload) SELECT ?,?,? WHERE ${condition.sql} ON CONFLICT(source,id) DO UPDATE SET payload=excluded.payload`).bind(source, config.id, JSON.stringify(config), ...condition.values)
    ]; if (calibrationEvent) statements.push(db().prepare(`INSERT INTO scale_events(id,source,scale_id,dish_id,at,received_at,kind,payload) SELECT ?,?,?,?,?,?,?,? WHERE ${condition.sql}`).bind(calibrationEvent.id,source,config.id,calibrationEvent.dishId,at,at,"correction",JSON.stringify(calibrationEvent),...condition.values)); const results = await db().batch(statements); if (results[0].meta.changes) return config;
  } throw new Error("设备配置正在更新，请重试");
}
export async function calibrate(source: Source, scaleId: string, tareG: number, fullG: number) { const config = (await readConfigs(source)).find(c => c.id === scaleId); if (!config) throw new Error("设备不存在"); if (config.noiseG >= tareG || config.noiseG >= fullG) throw new Error("皮重和满量必须大于噪声阈值"); return saveConfig(source, { ...config, tareG, fullG }); }
export async function readMinutes(source: Source, from: string, to: string): Promise<MinuteBucket[]> { const rows = await db().prepare("SELECT payload FROM scale_minutes WHERE source=? AND minute>=? AND minute<? ORDER BY minute").bind(source, new Date(from).toISOString(), new Date(to).toISOString()).all<{ payload: string }>(); return rows.results.map(r => JSON.parse(r.payload)); }
export async function readEvents(source: Source, from: string, to: string): Promise<WeightEvent[]> { const rows = await db().prepare("SELECT payload FROM scale_events WHERE source=? AND at>=? AND at<? ORDER BY at,id").bind(source, new Date(from).toISOString(), new Date(to).toISOString()).all<{ payload: string }>(); return rows.results.map(r => JSON.parse(r.payload) as WeightEvent).filter(e => !(e.kind === "take" && e.resolvedAt && Date.parse(e.resolvedAt) < Date.parse(to))); }
async function latest(source: Source, id: string) { const row = await db().prepare("SELECT revision,payload FROM scale_latest WHERE source=? AND scale_id=?").bind(source, id).first<Latest>(); return { revision: row?.revision ?? 0, state: row ? JSON.parse(row.payload) as DeviceState : newState() }; }
function gate(source: Source, scaleId: string, operation: string) { return { sql: "EXISTS(SELECT 1 FROM scale_latest WHERE source=? AND scale_id=? AND operation_id=?)", values: [source, scaleId, operation] }; }
export async function ingest(source: Source, samples: Sample[], receivedAt = new Date().toISOString()) {
  const configs = new Map((await readConfigs(source)).map(c => [c.id, c]));
  for (const sample of samples) if (!configs.get(sample.scaleId)?.enabled) throw new Error(`秤 ${sample.scaleId} 未配置或已停用`);
  let accepted = 0, ignored = 0, eventCount = 0;
  for (const input of samples) {
    const sample = { ...input, sampledAt: new Date(input.sampledAt).toISOString() };
    for (let attempt = 0; attempt < 5; attempt++) {
      const before = await latest(source, sample.scaleId), configRow = await db().prepare("SELECT payload FROM scale_configs WHERE source=? AND id=?").bind(source, sample.scaleId).first<{payload:string}>(), config = configRow ? JSON.parse(configRow.payload) as ScaleConfig : null;
      if (!config?.enabled) throw new Error(`秤 ${sample.scaleId} 未配置或已停用`);
      const result = measure(source, config, before.state, sample, receivedAt);
      if (!result.accepted) { ignored++; break; }
      const operation = crypto.randomUUID(), condition = gate(source, sample.scaleId, operation), minuteFrom = new Date(Math.floor(Math.max(Date.parse(sample.sampledAt) - 10000, Math.min(Date.parse(sample.sampledAt), Date.parse(before.state.sampledAt) || Date.parse(sample.sampledAt))) / 60000) * 60000).toISOString(), minuteTo = new Date(Date.parse(sample.sampledAt) + 60000).toISOString();
      // Query this bowl through the composite primary key instead of decoding every bowl 42 times per tick.
      const bucketRows = await db().prepare("SELECT payload FROM scale_minutes WHERE source=? AND scale_id=? AND dish_id=? AND minute>=? AND minute<? ORDER BY minute").bind(source, sample.scaleId, config.dishId, minuteFrom, minuteTo).all<{payload:string}>();
      const oldBuckets = bucketRows.results.map(row => JSON.parse(row.payload) as MinuteBucket);
      const buckets = updateBuckets(source, config, result, oldBuckets);
      const statements = [db().prepare("INSERT INTO scale_latest(source,scale_id,revision,operation_id,payload) VALUES (?,?,1,?,?) ON CONFLICT(source,scale_id) DO UPDATE SET revision=scale_latest.revision+1,operation_id=excluded.operation_id,payload=excluded.payload WHERE scale_latest.revision=?").bind(source, sample.scaleId, operation, JSON.stringify(result.state), before.revision), db().prepare(`INSERT INTO scale_samples(id,source,scale_id,sampled_at,received_at,payload) SELECT ?,?,?,?,?,? WHERE ${condition.sql} ON CONFLICT(id) DO NOTHING`).bind(`${source}:${sample.scaleId}:${sample.bootId}:${sample.sequence}`, source, sample.scaleId, sample.sampledAt, receivedAt, JSON.stringify(sample), ...condition.values)];
      for (const e of result.events) statements.push(db().prepare(`INSERT INTO scale_events(id,source,scale_id,dish_id,at,received_at,kind,payload) SELECT ?,?,?,?,?,?,?,? WHERE ${condition.sql} ON CONFLICT(id) DO NOTHING`).bind(e.id, source, e.scaleId, e.dishId, e.at, e.receivedAt, e.kind, JSON.stringify(e), ...condition.values));
      for (const b of buckets) statements.push(db().prepare(`INSERT INTO scale_minutes(source,scale_id,dish_id,minute,payload) SELECT ?,?,?,?,? WHERE ${condition.sql} ON CONFLICT(source,scale_id,dish_id,minute) DO UPDATE SET payload=excluded.payload`).bind(source, b.scaleId, b.dishId, b.minute, JSON.stringify(b), ...condition.values));
      const writes = await db().batch(statements);
      if (writes[0].meta.changes) { accepted++; eventCount += result.events.length; break; }
      if (attempt === 4) throw new Error("设备写入繁忙，请重试");
    }
  }
  return { success: true, source, accepted, ignored, events: eventCount };
}
function scaleView(config: ScaleConfig, state: DeviceState | undefined, now: string): ScaleView { const offline = !state || Date.parse(now) - Date.parse(state.sampledAt) > 10000 || Date.parse(now) - Date.parse(state.receivedAt) > 10000; const status = offline ? "offline" : state.mode; const visible = status === "active" || status === "empty" || status === "unstable" && state?.displayedNet !== null; return { ...config, status, netG: visible ? state?.displayedNet ?? null : null, percent: visible && state?.displayedNet !== null && state?.displayedNet !== undefined ? state.displayedNet / config.fullG * 100 : null, lastAt: state?.sampledAt ?? null, ...(state?.pendingId ? { pendingId: state.pendingId } : {}) }; }
function clipBuckets(buckets: MinuteBucket[], from: number, to: number) {
  return buckets.filter(b => Date.parse(b.minute) < to && Date.parse(b.minute) + 60000 > from).map(b => {
    const start = Date.parse(b.minute), overlap = Math.max(0, Math.min(to, start + 60000) - Math.max(from, start)), spans = (b as MinuteBucket & { observedSpans?: [number, number][] }).observedSpans;
    const observedSeconds = spans ? spans.reduce((sum, [a, z]) => sum + Math.max(0, Math.min(z, to) - Math.max(a, from)) / 1000, 0) : b.observedSeconds * overlap / 60000;
    return { ...b, observedSeconds, takeG: b.takeG * overlap / 60000, refillG: b.refillG * overlap / 60000 };
  });
}
export async function realtime(source: Source, now = new Date().toISOString()): Promise<Realtime> {
  const time = Date.parse(now), minuteStart = new Date(Math.floor(time / 60000) * 60000 - 30 * 60000).toISOString();
  const [configs, states, buckets, eventRows, recentEvents] = await Promise.all([readConfigs(source), db().prepare("SELECT scale_id,payload FROM scale_latest WHERE source=?").bind(source).all<{ scale_id: string; payload: string }>(), readMinutes(source, minuteStart, new Date(time + 60000).toISOString()), db().prepare("SELECT payload FROM scale_events WHERE source=? AND kind='pending' ORDER BY at").bind(source).all<{ payload: string }>(), readEvents(source, new Date(time - 5 * 60000).toISOString(), new Date(time + 1).toISOString())]);
  const latestStates = new Map(states.results.map(r => [r.scale_id, JSON.parse(r.payload) as DeviceState])), views = configs.filter(c => c.enabled).map(c => scaleView(c, latestStates.get(c.id), now));
  const dishes: DishRealtime[] = [...new Set(views.map(v => v.dishId))].map(id => {
    const scales = views.filter(v => v.dishId === id), valid = scales.filter(s => s.netG !== null), fullG = scales.reduce((n, s) => n + s.fullG, 0), allValid = valid.length === scales.length, remainingG = allValid ? valid.reduce((n, s) => n + s.netG!, 0) : null;
    const fiveFrom = time - 5 * 60000, expected = 300 * scales.length, recent = clipBuckets(buckets.filter(b => b.dishId === id), fiveFrom, time), rate = consumptionRate(recent, expected);
    const status: DishRealtime["status"] = scales.every(s => s.status === "offline") ? "offline" : scales.some(s => s.status === "anomaly") ? "anomaly" : !allValid ? "partial" : valid.every(s => s.netG! <= 3) ? "empty" : remainingG! / fullG < .2 ? "low" : "okay";
    const trend = Array.from({ length: 30 }, (_, i) => { const at = new Date(Math.floor(time / 60000) * 60000 - (29 - i) * 60000).toISOString(), bs = buckets.filter(b => b.dishId === id && b.minute === at), expected = (i === 29 ? Math.max(1, time % 60000 / 1000) : 60) * scales.length; return { at, takeG: bs.reduce((n, b) => n + b.takeG, 0), coverage: Math.min(1, bs.reduce((n, b) => n + b.observedSeconds, 0) / expected) }; });
    return { id, name: scales[0].dishName, remainingG, fullG, percent: remainingG !== null ? remainingG / fullG * 100 : null, rateGPerMinute: rate.rate === null ? null : recentEvents.filter(e => e.dishId === id && e.kind === "take").reduce((n, e) => n + e.weightG, 0) / recent.reduce((n, b) => n + b.observedSeconds, 0) * 60, coverage: rate.coverage, status, overfull: valid.some(s => s.netG! > s.fullG), scales, trend };
  });
  return { source, at: now, dishes, pending: eventRows.results.map(r => JSON.parse(r.payload) as WeightEvent).filter(e => !e.resolvedAt && menuDishFilter(configs)(e.dishId)) };
}
export async function dailySummary(source: Source, date: string, now = new Date().toISOString()): Promise<DailySummary> {
  const [settings, configs] = await Promise.all([readSettings(source), readConfigs(source)]), from = `${date}T00:00:00+08:00`, to = new Date(Date.parse(from) + 86400000).toISOString(), end = Math.min(Date.parse(now), Date.parse(`${date}T${settings.closeTime}:00+08:00`)), start = Date.parse(`${date}T${settings.openTime}:00+08:00`), elapsed = Math.max(0, end - start) / 1000, metricEnd = Math.min(Date.parse(now), Date.parse(to) - 1);
  const [events, minutes, live] = await Promise.all([readEvents(source, from, new Date(Math.max(Date.parse(from), metricEnd) + 1).toISOString()), readMinutes(source, from, to), localDate(now) === date && Math.abs(Date.now() - Date.parse(now)) < 10000 ? realtime(source, now) : Promise.resolve(null)]);
  const ids = [...new Set([...configs.map(c => c.dishId), ...events.map(e => e.dishId), ...minutes.map(b => b.dishId)])].filter(menuDishFilter(configs));
  const dishes = ids.map(dishId => { const ev = events.filter(e => e.dishId === dishId && Date.parse(e.at) <= metricEnd && Date.parse(e.receivedAt) <= Date.parse(now) && !(e.kind === "take" && e.resolvedAt && Date.parse(e.resolvedAt) <= Date.parse(now))), bs = clipBuckets(minutes.filter(b => b.dishId === dishId), start, end), scaleIds = [...new Set([...configs.filter(c => c.enabled && c.dishId === dishId).map(c => c.id), ...bs.map(b => b.scaleId)])], deviceCount = Math.max(1, scaleIds.length), sum = (kind: string) => ev.filter(e => e.kind === kind).reduce((n, e) => n + e.weightG, 0), last = [...minutes.filter(b => b.dishId === dishId && b.remainingG !== null && Date.parse((b as MinuteBucket & { remainingAt?: string }).remainingAt ?? b.minute) <= metricEnd && end - Date.parse((b as MinuteBucket & { remainingAt?: string }).remainingAt ?? b.minute) <= 10000 && Date.parse((b as MinuteBucket & { remainingAt?: string }).remainingAt ?? b.minute) <= end)].reverse(), lastByScale = new Map<string, number>(); for (const b of last) if (!lastByScale.has(b.scaleId)) lastByScale.set(b.scaleId, b.remainingG!); return { dishId, name: configs.find(c => c.dishId === dishId)?.dishName ?? dishId, takeG: sum("take"), refillG: sum("refill"), wasteG: sum("waste"), ageWasteG: ev.filter(e=>e.kind==="waste"&&e.reason==="display_age").reduce((n,e)=>n+e.weightG,0), retainedG: sum("retain"), remainingG: live ? live.dishes.find(d => d.id === dishId)?.remainingG ?? null : lastByScale.size >= deviceCount && configs.filter(c => c.enabled && c.dishId === dishId).every(c => lastByScale.has(c.id)) ? [...lastByScale.values()].reduce((n, g) => n + g, 0) : null, coverage: elapsed > 0 ? Math.min(1, bs.reduce((n, b) => n + b.observedSeconds, 0) / (elapsed * deviceCount)) : 0, emptyMinutes: dishEmptySeconds(bs, scaleIds, start, end) / 60, missingIntervals: Math.max(ev.filter(e => e.kind === "correction").length, bs.filter((b,i) => b.observedSeconds === 0 && (i === 0 || bs[i-1].observedSeconds > 0)).length), unresolved: ev.filter(e => e.kind === "pending" && (!e.resolvedAt || Date.parse(e.resolvedAt) > Date.parse(now))).length }; });
  return { source, date, asOf: now, final: Date.parse(now) >= Date.parse(`${date}T${settings.closeTime}:00+08:00`), dishes };
}
export async function resolve(source: Source, eventId: string, disposition: "waste" | "retain" | "correction", reason: "display_age" | "closing" | "other" = "other", classificationId?: string) {
  for (let attempt = 0; attempt < 5; attempt++) {
    const row = await db().prepare("SELECT payload FROM scale_events WHERE source=? AND id=? AND kind='pending'").bind(source, eventId).first<{ payload: string }>(); if (!row) throw new Error("待确认变化不存在或来源不匹配");
    const pending = JSON.parse(row.payload) as WeightEvent; if(disposition!=="correction"&&await hasActiveFreshness(pending.scaleId)) throw new Error("该碗位正在计时，请在限时更换中处理撤下；重量校正仍可在此核实"); if (pending.resolvedAt) throw new Error("该变化已处理"); if (disposition !== "correction" && pending.weightG <= 0) throw new Error("重量增加不能记为报损或保留，请标为校正");
    const before = await latest(source, pending.scaleId), state = structuredClone(before.state), operation = crypto.randomUUID(), at = new Date().toISOString(), condition = gate(source, pending.scaleId, operation); if (state.pendingId === eventId) { delete state.pendingId; state.mode = state.displayedNet === null ? "unstable" : state.displayedNet <= 3 ? "empty" : "active"; }
    const resolved = { ...pending, resolvedAt: at, resolution: disposition }, classification: WeightEvent = { ...pending, id: classificationId ?? `${pending.id}:resolved`, kind: disposition, weightG: Math.abs(pending.weightG), reason, receivedAt: at, resolvedAt: undefined, resolution: undefined };
    const results = await db().batch([db().prepare("UPDATE scale_latest SET revision=revision+1,operation_id=?,payload=? WHERE source=? AND scale_id=? AND revision=?").bind(operation, JSON.stringify(state), source, pending.scaleId, before.revision), db().prepare(`UPDATE scale_events SET payload=? WHERE id=? AND source=? AND ${condition.sql}`).bind(JSON.stringify(resolved), eventId, source, ...condition.values), db().prepare(`INSERT INTO scale_events(id,source,scale_id,dish_id,at,received_at,kind,payload) SELECT ?,?,?,?,?,?,?,? WHERE ${condition.sql} ON CONFLICT(id) DO NOTHING`).bind(classification.id, source, classification.scaleId, classification.dishId, classification.at, classification.receivedAt, classification.kind, JSON.stringify(classification), ...condition.values)]);
    if (results[0].meta.changes) return classification;
  }
  throw new Error("设备记录发生变化，请重试");
}
export async function manualReport(source: Source, scaleId: string, weightG: number, disposition: "waste" | "retain", reason: "display_age" | "closing" | "other", requestId: string) {
  const existingRequest = await db().prepare("SELECT payload FROM scale_events WHERE source=? AND id=?").bind(source, `${source}:manual:${requestId}`).first<{payload:string}>(); if (existingRequest) return { ...JSON.parse(existingRequest.payload), duplicate:true };
  const config = (await readConfigs(source)).find(c => c.id === scaleId); if (!config) throw new Error("设备不存在");
  if(await hasActiveFreshness(scaleId)) throw new Error("该碗位正在计时，请在限时更换中记录撤下，避免重复报损");
  const pending = (await realtime(source)).pending.filter(e => e.scaleId === scaleId && e.weightG > 0), matching = pending.find(e => Math.abs(e.weightG - weightG) <= config.noiseG);
  if (matching) { const result = await resolve(source, matching.id, disposition, reason, `${source}:manual:${requestId}`); return result; }
  if (pending.length) throw new Error("此秤存在待确认变化，请先按实际数量处理，避免重复扣量");
  const at = new Date().toISOString(), recent = (await readEvents(source, new Date(Date.parse(at) - 120000).toISOString(), new Date(Date.parse(at) + 1).toISOString())).filter(e => e.scaleId === scaleId && e.kind === "take" && !e.resolvedAt && Math.abs(e.weightG - weightG) <= config.noiseG);
  if (recent.length > 1) throw new Error("存在多个相同重量变化，无法唯一匹配，请处理待确认变化或稍后记录");
  if (recent.length === 1) {
    const measured = recent[0], e: WeightEvent = { ...measured, id: `${source}:manual:${requestId}`, kind: disposition, reason, receivedAt: at }, resolved = { ...measured, resolvedAt: at, resolution: disposition };
    const minute = new Date(Math.floor(Date.parse(measured.at) / 60000) * 60000).toISOString(), bucketRow = await db().prepare("SELECT payload FROM scale_minutes WHERE source=? AND scale_id=? AND dish_id=? AND minute=?").bind(source, scaleId, measured.dishId, minute).first<{ payload: string }>();
    const before = await latest(source, scaleId), operation = crypto.randomUUID(), condition = gate(source, scaleId, operation), statements = [db().prepare("UPDATE scale_latest SET revision=revision+1,operation_id=? WHERE source=? AND scale_id=? AND revision=?").bind(operation, source, scaleId, before.revision), db().prepare(`UPDATE scale_events SET payload=? WHERE id=? AND source=? AND ${condition.sql}`).bind(JSON.stringify(resolved), measured.id, source, ...condition.values), db().prepare(`INSERT INTO scale_events(id,source,scale_id,dish_id,at,received_at,kind,payload) SELECT ?,?,?,?,?,?,?,? WHERE ${condition.sql} ON CONFLICT(id) DO NOTHING`).bind(e.id, source, scaleId, e.dishId, e.at, at, e.kind, JSON.stringify(e), ...condition.values)];
    if (bucketRow) { const b = JSON.parse(bucketRow.payload) as MinuteBucket; b.takeG = Math.max(0, b.takeG - measured.weightG); statements.push(db().prepare(`UPDATE scale_minutes SET payload=? WHERE source=? AND scale_id=? AND dish_id=? AND minute=? AND ${condition.sql}`).bind(JSON.stringify(b), source, scaleId, measured.dishId, minute, ...condition.values)); }
    const results = await db().batch(statements); if (!results[0].meta.changes) throw new Error("设备记录发生变化，请重试"); return { ...e, replacedMeasuredChange: true };
  }
  // An annotation records physical disposal without inventing a weight delta or modifying the measurement baseline.
  const e: WeightEvent = { id: `${source}:manual:${requestId}`, source, scaleId, dishId: config.dishId, at, receivedAt: at, kind: disposition, weightG, reason };
  await db().prepare("INSERT INTO scale_events(id,source,scale_id,dish_id,at,received_at,kind,payload) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(e.id, source, scaleId, e.dishId, at, at, e.kind, JSON.stringify(e)).run(); return { ...e, annotationOnly: true };
}
export async function cleanup(now = new Date().toISOString()) { await db().batch([db().prepare("DELETE FROM scale_samples WHERE received_at<?").bind(new Date(Date.parse(now) - 86400000).toISOString()), db().prepare("DELETE FROM scale_minutes WHERE minute<?").bind(new Date(Date.parse(now) - 90 * 86400000).toISOString())]); }
