export type Source = "live";
export type ScaleStatus = "active" | "empty" | "removed" | "offline" | "unstable" | "anomaly";
export interface ScaleConfig { id:string; dishId:string; dishName:string; tareG:number; fullG:number; noiseG:number; enabled:boolean; position?:number; updatedAt:string; }
export interface Sample { scaleId:string; bootId:string; sequence:number; sampledAt:string; grossG:number; }
export interface ScaleView extends ScaleConfig { netG:number|null; percent:number|null; status:ScaleStatus; lastAt:string|null; pendingId?:string; }
export interface WeightEvent { batchId?:string; removalScope?:"partial"|"full"; id:string; source:Source; scaleId:string; dishId:string; at:string; receivedAt:string; kind:"opening"|"take"|"refill"|"pending"|"waste"|"retain"|"correction"; weightG:number; reason?:"display_age"|"closing"|"other"; resolvedAt?:string; resolution?:string; }
export interface MinuteBucket { source:Source; scaleId:string; dishId:string; minute:string; takeG:number; refillG:number; observedSeconds:number; emptySeconds:number; remainingG:number|null; }
export interface DishRealtime { id:string; name:string; remainingG:number|null; fullG:number; percent:number|null; rateGPerMinute:number|null; coverage:number; status:"okay"|"low"|"empty"|"offline"|"partial"|"anomaly"; overfull:boolean; scales:ScaleView[]; trend:{at:string;takeG:number;coverage:number}[]; }
export interface Realtime { scenario?:{datasetId:string;start:string;end:string;asOf:string}; simulation?:{enabled:boolean;provider:string}|null; source:Source; at:string; dishes:DishRealtime[]; pending:WeightEvent[]; }
export interface DailyDish { ageWasteG?:number; dishId:string; name:string; takeG:number; refillG:number; wasteG:number; retainedG:number; remainingG:number|null; coverage:number; emptyMinutes:number; unresolved:number; missingIntervals?:number; }
export interface DailySummary { source:Source; date:string; asOf:string; final:boolean; dishes:DailyDish[]; }
export interface ForecastLine { dishId:string; name:string; unit:"g"; demand:number|null; low:number|null; high:number|null; suggested:number|null; samples:number; confidence:"observing"|"limited"|"reference"; explanation:string; }
export interface ForecastView { provenance?:"historical-replay"; id:string; source:Source; originDate:string; targetDate:string; cutoff:string; generatedAt:string; late:boolean; buffer:number; lines:ForecastLine[]; }
export interface PlanView { forecastId:string; date:string; at:string; lines:{dishId:string;quantity:number;reason:string}[]; }
export interface ExecutionView { date:string; dishId:string; prepared:number; added:number; kitchenRetained:number; ageWaste:number; closingWaste:number; otherWaste:number; note:string; at:string; }
export interface PreferenceView { supplyFeedbackError?:string; supplyFeedback?:{asOf:string;suggestions:import("../freshness/model").SupplySuggestion[];decisions:import("../freshness/model").SupplyDecision[]}; history?:{phase:string;simulation?:{enabled:boolean};manifest:{parameters:{start:string;end:string;mode?:string}}}|null; source:Source; asOf:string; dates:string[]; daily?:DailySummary; assessment?:{date:string;dishId:string;preparedG:number;scaleRefillG:number|null;planDifference:number|null;predictionError:number|null}[]; profile:{dishId:string;name:string;unit:"g";weightedTake:number|null;takeG:number;share:number|null;status:string;samples:number;history:{date:string;quantity:number|null;supply:string}[]}[]; forecasts:ForecastView[]; plans:PlanView[]; executions:ExecutionView[]; }
