import { env } from "cloudflare:workers";
import type { Source, DailySummary } from "../scales/types.ts";
import { readConfigs, dailySummary, readEvents, readSettings } from "../scales/repository.ts";
import type { Catalog, Confirmation, Dataset, DishDay, Execution, Forecast, StoreDay } from "./types.ts";
import { cutoffAt, localDate, shiftDate } from "./types.ts";
import { predict, profiles } from "./model.ts";
import { validateDataset } from "./contract.ts";
import { menuDishFilter, menuForecast } from "../scales/menu.ts";
function db(){if(!env.DB)throw new Error("数据库未连接");return env.DB;}
type Table="weight_catalog"|"weight_daily"|"weight_snapshots"|"weight_models"|"weight_forecasts"|"weight_plans"|"weight_executions"|"weight_evaluations";
export async function rows<T>(table:Table,source:Source){const r=await db().prepare(`SELECT payload FROM ${table} WHERE source = ? ORDER BY id`).bind(source).all<{payload:string}>();const records=r.results.map(r=>JSON.parse(r.payload) as T);
 if(!["weight_forecasts","weight_plans","weight_executions"].includes(table))return records;
 const configs=await readConfigs(source),allowed=menuDishFilter(configs);
 return records.filter(record=>{const row=record as {dishId?:string};return !row.dishId||allowed(row.dishId);}).map(record=>{
  if(table==="weight_forecasts")return menuForecast(record as unknown as Forecast,configs) as unknown as T;
  const row=record as T & {lines?:{dishId:string}[]};return row.lines?{...row,lines:row.lines.filter(line=>allowed(line.dishId))}:record;
 });}
function put(table:Table,source:Source,id:string,payload:unknown,date?:string,itemId?:string){const columns=["id","source",...(date?["date"]:[]),...(itemId!==undefined?["item_id"]:[]),"payload"];return db().prepare(`INSERT INTO ${table} (${columns.join(",")}) VALUES (${columns.map(()=>"?").join(",")}) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload`).bind(id,source,...(date?[date]:[]),...(itemId!==undefined?[itemId]:[]),JSON.stringify(payload));}
function putOnce(table:Table,source:Source,id:string,payload:unknown,date:string,itemId:string){return db().prepare(`INSERT INTO ${table}(id,source,date,item_id,payload) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(id,source,date,itemId,JSON.stringify(payload));}
function leasedPut(table:"weight_forecasts"|"weight_models",source:Source,id:string,payload:unknown,key:string,lease:string,date?:string){const columns=["id","source",...(date?["date"]:[]),"payload"],values=[id,source,...(date?[date]:[]),JSON.stringify(payload)];return db().prepare(`INSERT INTO ${table}(${columns.join(",")}) SELECT ${columns.map(()=>"?").join(",")} WHERE EXISTS(SELECT 1 FROM weight_jobs WHERE id=? AND lease=? AND status='running')`).bind(...values,key,lease);}
type Snapshot={date:string;dishId?:string;take20?:number|null;snapshotAt:string;capturedAt?:string};
export async function readDataset(source:Source,includeRetired=false):Promise<Dataset>{const [catalog,daily,snapshots]=await Promise.all([rows<Catalog>("weight_catalog",source),rows<StoreDay|DishDay>("weight_daily",source),rows<Snapshot>("weight_snapshots",source)]);const stores=daily.filter(d=>!("dishId" in d)) as StoreDay[],days=daily.filter(d=>"dishId" in d) as DishDay[];
 for(const snapshot of snapshots){if(snapshot.dishId){const d=days.find(d=>d.date===snapshot.date&&d.dishId===snapshot.dishId);if(d){d.take20=snapshot.take20??null;d.snapshotAt=snapshot.snapshotAt;}else days.push({date:snapshot.date,dishId:snapshot.dishId,take20:snapshot.take20??null,snapshotAt:snapshot.snapshotAt,takeFinal:null,takeG:null,opening:null,replenished:null,waste:null,closing:null,supply:"unknown",stockoutMinutes:null,status:"partial",finalAt:`${snapshot.date}T23:59:59+08:00`});}else if(!stores.some(s=>s.date===snapshot.date))stores.push({date:snapshot.date,status:"open",snapshotAt:snapshot.snapshotAt,finalAt:`${snapshot.date}T23:59:59+08:00`});}
 const configs=includeRetired?[]:await readConfigs(source),allowed=includeRetired?()=>true:menuDishFilter(configs);
 // Device setup defines the menu immediately, even before the first daily capture.
 for(const c of configs.filter(c=>c.enabled))if(!catalog.some(d=>d.id===c.dishId))catalog.push({id:c.dishId,name:c.dishName,category:"",unit:"g",pieceWeightG:null,launchDate:localDate(c.updatedAt)});
 return {catalog:catalog.filter(c=>allowed(c.id)),stores,days:days.filter(d=>allowed(d.dishId))};}
export async function saveDataset(source:Source,data:Dataset){validateDataset(data);const existing=await readDataset(source,true),statements:D1PreparedStatement[]=[];
 for(const c of data.catalog){const old=existing.catalog.find(d=>d.id===c.id);if(old&&old.pieceWeightG!==c.pieceWeightG)throw new Error(`历史菜品重量单位不同 ${c.id}`);statements.push(put("weight_catalog",source,`${source}:${c.id}`,c));}
 for(const s of data.stores){statements.push(put("weight_daily",source,`${source}:${s.date}:store`,s,s.date,"store"));statements.push(put("weight_snapshots",source,`${source}:${s.date}:store`,{date:s.date,snapshotAt:s.snapshotAt},s.date,"store"));}
 for(const d of data.days){const old=existing.days.find(v=>v.date===d.date&&v.dishId===d.dishId);if(old&&old.takeFinal!==null&&JSON.stringify(old)!==JSON.stringify(d))throw new Error(`已存全天记录不可覆盖 ${d.date}/${d.dishId}`);statements.push(put("weight_daily",source,`${source}:${d.date}:${d.dishId}`,d,d.date,d.dishId));statements.push(put("weight_snapshots",source,`${source}:${d.date}:${d.dishId}`,{date:d.date,dishId:d.dishId,take20:d.take20,snapshotAt:d.snapshotAt},d.date,d.dishId));}
 await db().batch(statements);return {catalog:data.catalog.length,stores:data.stores.length,days:data.days.length};}
export async function generate(source:Source,origin:string,buffer=.1,force=false,scenarioReplay=false){const now=new Date().toISOString(),cutoff=cutoffAt(origin);if(!scenarioReplay&&Date.parse(cutoff)>Date.parse(now))throw new Error("尚未到该日期20:00，不能生成未来截止时点的预测");
 const key=`forecast:${source}:${origin}`,lease=crypto.randomUUID();
 const claimed=await db().prepare("INSERT INTO weight_jobs(id,source,status,lease,updated_at) VALUES (?,?,'running',?,?) ON CONFLICT(id) DO UPDATE SET status='running',lease=excluded.lease,updated_at=excluded.updated_at,error=NULL WHERE weight_jobs.status='failed' OR (weight_jobs.status='running' AND weight_jobs.updated_at < ?) OR (weight_jobs.status='complete' AND ?=1)").bind(key,source,lease,now,new Date(Date.now()-300000).toISOString(),force?1:0).run();
 if(!claimed.meta.changes){const existing=(await rows<Forecast>("weight_forecasts",source)).filter(f=>f.originDate===origin).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt))[0];if(existing)return existing;throw new Error("该日期预测正在生成，请稍后重试");}
 try{const data=await readDataset(source);if(!data.catalog.length||!data.days.some(d=>d.date===origin))throw new Error("没有该日期的菜品记录，请先导入数据或采集20:00快照");const evaluations=await rows<{lambdas?:Record<string,number>;split?:{validation:string[]};generatedAt?:string}>("weight_evaluations",source);const evaluation=evaluations.filter(r=>r.lambdas&&r.split?.validation.at(-1)&&r.split.validation.at(-1)!<origin).sort((a,b)=>(b.generatedAt??"").localeCompare(a.generatedAt??""))[0];
 const forecast:Forecast=menuForecast({id:crypto.randomUUID(),source,originDate:origin,targetDate:shiftDate(origin,1),cutoff,generatedAt:now,late:Date.parse(now)-Date.parse(cutoff)>300000,buffer,lines:predict(data,origin,buffer,evaluation?.lambdas)},await readConfigs(source));
 const leaseCheck=await db().prepare("SELECT lease FROM weight_jobs WHERE id=?").bind(key).first<{lease:string}>();if(leaseCheck?.lease!==lease)throw new Error("任务租约已更换，请重试");
 const saved=await db().batch([leasedPut("weight_forecasts",source,forecast.id,forecast,key,lease,forecast.targetDate),...forecast.lines.filter(l=>l.model).map(l=>leasedPut("weight_models",source,`${source}:${forecast.id}:${l.dishId}`,{forecastId:forecast.id,at:now,...l.model},key,lease)),db().prepare("UPDATE weight_jobs SET status='complete',updated_at=? WHERE id=? AND lease=?").bind(now,key,lease)]);if(!saved[0].meta.changes)throw new Error("任务租约已更换，请重试");return forecast;
 }catch(e){await db().prepare("UPDATE weight_jobs SET status='failed',error=?,updated_at=? WHERE id=? AND lease=?").bind(e instanceof Error?e.message:"模型失败",new Date().toISOString(),key,lease).run();throw e;}}
export async function confirm(source:Source,input:Confirmation){const forecast=(await rows<Forecast>("weight_forecasts",source)).find(f=>f.id===input.forecastId);if(!forecast)throw new Error("预测不存在或来源不匹配");if(forecast.targetDate!==input.date)throw new Error("计划日期不匹配");if(new Set(input.lines.map(l=>l.dishId)).size!==input.lines.length||input.lines.length!==forecast.lines.length)throw new Error("请确认全部菜品，每道菜只能出现一次");for(const l of input.lines){const f=forecast.lines.find(f=>f.dishId===l.dishId);if(!f)throw new Error("未知菜品");if((f.suggested===null||l.quantity!==f.suggested)&&!l.reason.trim())throw new Error("修改建议量或试供量时请填写理由");}await put("weight_plans",source,`${source}:${input.date}:${crypto.randomUUID()}`,input,input.date).run();return input;}
export async function execution(source:Source,input:Execution){const data=await readDataset(source);if(!data.catalog.some(c=>c.id===input.dishId))throw new Error("未知菜品");if(input.ageWaste+input.closingWaste+input.otherWaste+input.kitchenRetained>input.prepared+input.added)throw new Error("后厨保留与总报损超过实际备料和追加量");await put("weight_executions",source,`${source}:${input.date}:${input.dishId}`,input,input.date).run();return input;}
export async function dashboard(source:Source,asOf:string){const [data,forecasts,plans,executions,evaluations]=await Promise.all([readDataset(source),rows<Forecast>("weight_forecasts",source),rows<Confirmation>("weight_plans",source),rows<Execution>("weight_executions",source),rows<{metrics?:unknown;generatedAt?:string}>("weight_evaluations",source)]);const date=localDate(asOf),selected=data.days.filter(d=>d.date===date&&Date.parse(d.finalAt)<=Date.parse(asOf)),measured=await dailySummary(source,date,asOf);
 // Calendar reports retain closing disposal; training uses the separate business-close snapshot.
 const hasMeasured=measured.dishes.some(d=>d.coverage>0||d.takeG>0||d.refillG>0||d.wasteG>0||d.retainedG>0||d.remainingG!==null||d.unresolved>0||(d.missingIntervals??0)>0);
 const daily:DailySummary=hasMeasured||!selected.length?measured:{source,date,asOf,final:selected.length>0&&selected.every(d=>d.status==="complete"||d.status==="closed"||d.status==="not_launched"),dishes:selected.map(d=>({dishId:d.dishId,name:data.catalog.find(c=>c.id===d.dishId)?.name??d.dishId,takeG:d.takeFinal??0,refillG:d.replenished??0,wasteG:d.waste??0,retainedG:d.retainedKitchen??0,remainingG:d.closing,coverage:d.status==="complete"?1:0,emptyMinutes:d.stockoutMinutes??0,unresolved:d.status==="partial"||d.status==="missing"?1:0}))};
 // Missing historical observations remain unknown, but use the same current menu.
 if(daily!==measured){const byId=new Map(daily.dishes.map(d=>[d.dishId,d]));daily.dishes=[...measured.dishes.map(d=>byId.get(d.dishId)??d),...daily.dishes.filter(d=>!measured.dishes.some(m=>m.dishId===d.dishId))];}
 const assessment=executions.map(e=>{const day=data.days.find(d=>d.date===e.date&&d.dishId===e.dishId&&Date.parse(d.finalAt)<=Date.parse(asOf)),confirmed=plans.filter(p=>p.date===e.date).sort((a,b)=>b.at.localeCompare(a.at))[0],plan=confirmed?.lines.find(l=>l.dishId===e.dishId),forecast=(confirmed?forecasts.find(f=>f.id===confirmed.forecastId):forecasts.filter(f=>f.targetDate===e.date).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt))[0])?.lines.find(l=>l.dishId===e.dishId);return {date:e.date,dishId:e.dishId,scaleRefillG:day?.replenished??null,preparedG:e.prepared+e.added,planDifference:plan?e.prepared-plan.quantity:null,predictionError:day?.status==="complete"&&day.supply==="adequate"&&forecast?.demand!=null&&day.takeFinal!==null?day.takeFinal-forecast.demand:null};});
 return {source,asOf,catalog:data.catalog,dates:[...new Set([...data.days.map(d=>d.date),...data.stores.map(d=>d.date)])].sort(),profile:profiles(data,asOf),forecasts:forecasts.sort((a,b)=>b.targetDate.localeCompare(a.targetDate)||b.generatedAt.localeCompare(a.generatedAt)),plans:plans.sort((a,b)=>b.at.localeCompare(a.at)),executions,assessment,daily,days:data.days.filter(d=>Date.parse(d.finalAt)<=Date.parse(asOf)),evaluation:evaluations.find(e=>e.metrics)??null};}
// Live capture depends only on scale records, never archived orders or business snapshots.
export async function capture(source:Source,date:string,snapshot:boolean){const now=new Date().toISOString(),settings=await readSettings(source),cutoff=snapshot?cutoffAt(date):`${date}T${settings.closeTime}:00+08:00`;const [configs,data,summary,events]=await Promise.all([readConfigs(source),readDataset(source,true),dailySummary(source,date,cutoff),readEvents(source,`${date}T00:00:00+08:00`,new Date(Math.min(Date.parse(cutoff)+1,Date.parse(`${shiftDate(date,1)}T00:00:00+08:00`))).toISOString())]);const active=configs.filter(c=>c.enabled);if(!active.length)return;
 const statements:D1PreparedStatement[]=[],late=snapshot&&Date.parse(now)-Date.parse(cutoff)>300000;
 const dishes=[...new Map(active.map(c=>[c.dishId,c])).values()];for(const c of dishes)if(!data.catalog.some(d=>d.id===c.dishId))statements.push(put("weight_catalog",source,`${source}:${c.dishId}`,{id:c.dishId,name:c.dishName,category:"",unit:"g",pieceWeightG:null,launchDate:date}));
 const existingSnapshots=await rows<Snapshot>("weight_snapshots",source);
 if(snapshot){if(!existingSnapshots.some(s=>s.date===date&&!s.dishId))statements.push(putOnce("weight_snapshots",source,`${source}:${date}:store`,{date,snapshotAt:late?now:cutoff,capturedAt:now},date,"store"));for(const c of dishes){if(existingSnapshots.some(s=>s.date===date&&s.dishId===c.dishId))continue;const d=summary.dishes.find(d=>d.dishId===c.dishId),known=events.filter(e=>e.dishId===c.dishId&&e.kind==="take"&&Date.parse(e.at)<=Date.parse(cutoff)&&Date.parse(e.receivedAt)<=Date.parse(cutoff));const take20=!late&&d&&d.coverage>=.95&&d.unresolved===0&&!(d.missingIntervals??0)&&!events.some(e=>e.dishId===c.dishId&&e.kind==="correction"&&Date.parse(e.at)<=Date.parse(cutoff)&&Date.parse(e.receivedAt)<=Date.parse(cutoff))?known.reduce((n,e)=>n+e.weightG,0):null;statements.push(putOnce("weight_snapshots",source,`${source}:${date}:${c.dishId}`,{date,dishId:c.dishId,take20,snapshotAt:late?now:cutoff,capturedAt:now},date,c.dishId));}}
 else {if(Date.parse(now)<Date.parse(`${date}T${settings.closeTime}:00+08:00`)+600000)return;if(data.stores.some(s=>s.date===date&&Date.parse(s.finalAt)>Date.parse(`${date}T${settings.closeTime}:00+08:00`)))return;
 const store:StoreDay={date,status:"open",snapshotAt:data.stores.find(s=>s.date===date)?.snapshotAt??cutoffAt(date),finalAt:now};statements.push(putOnce("weight_daily",source,`${source}:${date}:store`,store,date,"store"));
 for(const c of dishes){const d=summary.dishes.find(d=>d.dishId===c.dishId),ev=events.filter(e=>e.dishId===c.dishId&&Date.parse(e.at)<=Date.parse(`${date}T${settings.closeTime}:00+08:00`)&&Date.parse(e.receivedAt)<=Date.parse(now)),sum=(kind:string)=>ev.filter(e=>e.kind===kind).reduce((n,e)=>n+e.weightG,0),opening=sum("opening"),replenished=sum("refill"),take=sum("take"),waste=sum("waste"),retained=sum("retain"),closing=d?.remainingG??null;const conserved=closing!==null&&Math.abs(opening+replenished-take-waste-retained-closing)<=Math.max(3,dishes.length*3);const good=!!d&&d.coverage>=.95&&d.emptyMinutes===0&&d.unresolved===0&&!(d.missingIntervals??0)&&!ev.some(e=>e.kind==="correction")&&conserved;const existing=data.days.find(d=>d.date===date&&d.dishId===c.dishId);
 const record:DishDay={date,dishId:c.dishId,status:good?"complete":"partial",take20:existing?.take20??null,takeFinal:d&&d.coverage>0?take:null,takeG:d&&d.coverage>0?take:null,opening:ev.length?opening:null,replenished:ev.length?replenished:null,waste:ev.length?waste:null,closing,supply:good?"adequate":d&&d.emptyMinutes>0?"stockout":"unknown",stockoutMinutes:d?.emptyMinutes??null,snapshotAt:existing?.snapshotAt??cutoffAt(date),finalAt:now,ageWaste:ev.filter(e=>e.kind==="waste"&&e.reason==="display_age").reduce((n,e)=>n+e.weightG,0),closingWaste:ev.filter(e=>e.kind==="waste"&&e.reason==="closing").reduce((n,e)=>n+e.weightG,0),retainedKitchen:retained};statements.push(putOnce("weight_daily",source,`${source}:${date}:${c.dishId}`,record,date,c.dishId));}}
 if(statements.length)await db().batch(statements);}
