import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildCurrentProfile,type CurrentObservation} from '../lib/analysis/current-profile.ts';
import {shiftDate,type Dataset,type DishDay} from '../lib/preferences/types.ts';
const asOf='2026-10-04T05:00:00Z';
function data():Dataset {const dates=Array.from({length:42},(_,i)=>shiftDate('2026-08-23',i));return {catalog:['a','b'].map(id=>({id,name:id,category:'',unit:'g',pieceWeightG:null,launchDate:'2026-01-01'})),stores:dates.map(date=>({date,status:'open',snapshotAt:date+'T20:00:00+08:00',finalAt:date+'T23:00:00+08:00'})),days:dates.flatMap(date=>['a','b'].map(dishId=>({date,dishId,status:'complete',takeFinal:100,takeG:100,take20:50,supply:'adequate',stockoutMinutes:0,snapshotAt:date+'T20:00:00+08:00',finalAt:date+'T23:00:00+08:00'} as DishDay)))};}
function live():CurrentObservation{return {date:'2026-10-04',open:true,elapsedMinutes:120,lastObservedAt:asOf,error:null,dishes:['a','b'].map(dishId=>({dishId,takeG:dishId==='a'?900:100,coverage:1,emptyMinutes:0,unresolved:0,missingIntervals:0,fresh:true}))};}
test('current estimate weights recent history more and keeps modeled shares normalized',()=>{const d=data();d.days=d.days.map(r=>({...r,takeFinal:r.dishId==='a'&&r.date>='2026-09-25'?500:100}));const r=buildCurrentProfile(d,asOf);assert(r.dishes[0].share!>r.dishes[0].longTermShare!);assert.equal(r.current.state,'historical');assert(Math.abs(r.dishes.reduce((s,d)=>s+(d.currentShare??0),0)-1)<1e-10);});
test('qualified current observation updates same cohort with bounded weight',()=>{const r=buildCurrentProfile(data(),asOf,[],undefined,live());assert.equal(r.current.liveWeight,.5);assert.equal(r.current.state,'live');assert(Math.abs(r.dishes[0].currentShare!-.7)<1e-10);assert(Math.abs(r.dishes[1].currentShare!-.3)<1e-10);assert(Math.abs(r.dishes[0].changePoints!-20)<1e-10);});
test('missing, low coverage, empty, unresolved, correction and stale devices cannot alter prior',()=>{for(const change of [{coverage:.94},{emptyMinutes:1},{unresolved:1},{missingIntervals:1},{fresh:false},{takeG:NaN}]){const l=live();Object.assign(l.dishes[0],change);const r=buildCurrentProfile(data(),asOf,[],undefined,l);assert.equal(r.current.liveWeight,0);assert.equal(r.dishes[0].currentShare,.5);}const l=live();l.dishes.pop();assert.equal(buildCurrentProfile(data(),asOf,[],undefined,l).current.liveWeight,0);});
test('outside hours, wrong day, short observation, zero totals and old history stay historical',()=>{for(const l of [{...live(),open:false},{...live(),date:'2026-10-03'},{...live(),elapsedMinutes:29},{...live(),dishes:live().dishes.map(d=>({...d,takeG:0}))}])assert.equal(buildCurrentProfile(data(),asOf,[],undefined,l).current.liveWeight,0);const r=buildCurrentProfile(data(),'2026-11-04T05:00:00Z');assert.equal(r.current.state,'stale');});
test('today never enters historical prior and untrained dishes stay unknown',()=>{const d=data(),base=buildCurrentProfile(d,asOf);d.days.push({...d.days[0],date:'2026-10-04',finalAt:'2026-10-04T01:00:00Z',takeFinal:999999});d.stores.push({date:'2026-10-04',status:'open',snapshotAt:asOf,finalAt:'2026-10-04T01:00:00Z'});const r=buildCurrentProfile(d,asOf);assert.equal(r.dishes[0].estimateG,base.dishes[0].estimateG);d.days=d.days.filter(r=>r.dishId==='a'||r.date<'2026-09-01');assert.equal(buildCurrentProfile(d,asOf).dishes[1].currentShare,null);});

test('zero historical denominator never claims live correction',()=>{const d=data();d.days=d.days.map(r=>({...r,takeFinal:0}));const r=buildCurrentProfile(d,asOf,[],undefined,live());assert.equal(r.current.liveWeight,0);assert(r.dishes.every(d=>d.currentShare===null));assert.match(r.current.reason,/合计为零/);});
