import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import type { Dataset,DishDay } from '../lib/preferences/types.ts';
import { shiftDate } from '../lib/preferences/types.ts';
import { buildOverallProfile,overallMealQuery } from '../lib/analysis/overall.ts';
import { overallAnalysisRequestSchema,analysisRequestSchema } from '../lib/analysis/contract.ts';
import { runAgent,type Complete } from '../lib/analysis/agent.ts';
function fixture():Dataset {const dates=Array.from({length:42},(_,i)=>shiftDate('2026-08-01',i));return {catalog:['a','b'].map(id=>({id,name:'同名菜',category:'同类',unit:'g',pieceWeightG:null,launchDate:'2026-01-01'})),stores:dates.map(date=>({date,status:'open',snapshotAt:date+'T20:00:00+08:00',finalAt:date+'T23:00:00+08:00'})),days:dates.flatMap((date,i)=>['a',...(i<21?['b']:[])].map(dishId=>({date,dishId,status:'complete',takeFinal:100,takeG:100,take20:70,opening:0,replenished:100,waste:0,closing:0,supply:'adequate',stockoutMinutes:0,snapshotAt:date+'T20:00:00+08:00',finalAt:date+'T23:00:00+08:00'} as DishDay)))};}
const asOf='2026-10-04T01:00:00Z';
test('overall models equal daily means equally despite different history lengths, preserves IDs',()=>{const r=buildOverallProfile(fixture(),asOf);assert.equal(r.modeledCount,2);assert.deepEqual(r.dishes.map(d=>d.samples),[42,21]);assert.deepEqual(r.dishes.map(d=>d.estimateG),[100,100]);assert.deepEqual(r.dishes.map(d=>d.share),[.5,.5]);});
test('weekday estimates shrink to baseline with exactly seven pseudo-days',()=>{const data=fixture();data.days=data.days.map(d=>({...d,takeFinal:new Date(d.date+'T00:00:00Z').getUTCDay()===1?240:100}));const d=buildOverallProfile(data,asOf).dishes[0];const monday=data.days.filter(r=>r.dishId==='a'&&new Date(r.date+'T00:00:00Z').getUTCDay()===1);assert.equal(d.weekdays[0].name,'周一');assert.equal(d.weekdays[6].name,'周日');assert.equal(d.weekdays[0].estimateG,(monday.length*240+7*d.estimateG!)/(monday.length+7));});
test('eligibility excludes stockouts, partial, unknown, closed, future, unavailable and prelaunch records',()=>{const data=fixture();data.days=data.days.filter(d=>d.dishId==='a');const before=data.days.length;data.days[0].supply='stockout';data.days[1].status='partial';data.days[2].takeFinal=null;data.stores[3].status='closed';data.days[4].finalAt='2099-01-01T00:00:00Z';data.stores[5].finalAt='2099-01-01T00:00:00Z';data.catalog[0].launchDate='2026-08-07';data.days.push({...data.days[10],date:'2099-01-01',finalAt:'2026-01-01T00:00:00Z'});const r=buildOverallProfile(data,asOf);assert.equal(r.dishes[0].samples,before-6);assert.equal(r.endDate,'2026-09-11');assert.equal(r.dishes[1].estimateG,null);});
test('twenty dates stay learning, true zero is modeled, empty denominator remains null',()=>{const data=fixture();data.days=data.days.filter(d=>d.dishId==='a'||d.date!=='2026-08-01');data.days=data.days.map(d=>({...d,takeFinal:0}));const r=buildOverallProfile(data,asOf);assert.equal(r.dishes[0].estimateG,0);assert.equal(r.dishes[0].share,null);assert.equal(r.dishes[1].samples,20);assert.equal(r.dishes[1].estimateG,null);assert.equal(r.learningCount,1);assert.equal(buildOverallProfile({catalog:[],stores:[],days:[]},asOf).startDate,null);});
test('zero weekday samples use baseline without inventing evidence and modeled shares exclude learning',()=>{const data=fixture();data.days=data.days.filter(d=>d.dishId==='a'&&new Date(d.date+'T00:00:00Z').getUTCDay()!==1);const r=buildOverallProfile(data,asOf);assert.equal(r.dishes[0].weekdays[0].samples,0);assert.equal(r.dishes[0].weekdays[0].estimateG,100);assert.equal(r.dishes[0].share,1);assert.equal(r.dishes[1].share,null);});
test('period SQL excludes wrong source, missing observations and unfinished minutes',()=>{const db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE scale_minutes(source TEXT,minute TEXT,dish_id TEXT,payload TEXT)');const insert=db.prepare('INSERT INTO scale_minutes VALUES(?,?,?,?)');for(const [at,g,seconds,source] of [['2026-10-03T03:00:00Z',20,60,'live'],['2026-10-03T09:00:00Z',30,60,'live'],['2026-10-03T09:01:00Z',999,0,'live'],['2026-10-03T09:02:00Z',999,60,'demo'],['2026-10-03T09:03:00Z',999,60,'live']] as const)insert.run(source,at,'a',JSON.stringify({takeG:g,observedSeconds:seconds}));const rows=db.prepare(overallMealQuery).all('2026-10-03T00:00:00Z','2026-10-03T09:03:00Z');assert.deepEqual(rows.map(r=>[r.period,r.grams]),[[1,20],[3,30]]);}finally{db.close();}});
test('overall request cannot carry arbitrary dates and ordinary scopes retain 31-day limit',()=>{assert(overallAnalysisRequestSchema.safeParse({mode:'overall',question:'画像'}).success);assert(!overallAnalysisRequestSchema.safeParse({mode:'overall',question:'画像',startDate:'2000-01-01'}).success);assert(!analysisRequestSchema.safeParse({question:'画像',startDate:'2026-01-01',endDate:'2026-09-01'}).success);});
test('overall agent advertises overall and freshness tools and blocks injected short-scope calls',async()=>{let turn=0;const names:string[]=[];const complete:Complete=async(messages,tools)=>{assert.deepEqual(tools.map(t=>t.function.name),['freshness_feedback','overall_profile']);turn++;if(turn===1)return {role:'assistant',tool_calls:[{id:'bad',type:'function',function:{name:'daily_statistics',arguments:'{}'}},{id:'ok',type:'function',function:{name:'overall_profile',arguments:'{}'}},{id:'feedback',type:'function',function:{name:'freshness_feedback',arguments:'{}'}}]};assert(messages.some(m=>m.role==='tool'&&m.content?.includes('该模式不允许')));return {role:'assistant',content:'模型估计，不是个人偏好。[E1]'};};const r=await runAgent({mode:'overall',question:'整体画像',startDate:'2026-01-01',endDate:'2026-10-04'},'mock',complete,async name=>{names.push(name);return {title:'整体',data:{modeledCount:1}};},new AbortController().signal,asOf);assert.deepEqual(names,['overall_profile','freshness_feedback']);assert.equal(r.scope.mode,'overall');});
