import { test } from "node:test";
import assert from "node:assert/strict";
import { consumptionRate, dishEmptySeconds, measure, minuteParts, newState, updateBuckets, type DeviceState } from "../lib/scales/engine.ts";
import type { MinuteBucket, ScaleConfig, WeightEvent } from "../lib/scales/types.ts";
const config: ScaleConfig = { id: "s1", dishId: "d", dishName: "菜", tareG: 300, fullG: 1000, noiseG: 3, enabled: true, updatedAt: "2026-10-03T11:00:00+08:00" };
function stream() { let state = newState(), sequence = 0, seconds = 0, bootId = "boot", buckets: MinuteBucket[] = []; const events: WeightEvent[] = []; return { get state() { return state; }, get events() { return events; }, get buckets() { return buckets; }, sample(grossG: number, gap = 1) { seconds += gap; const sampledAt = new Date(Date.parse("2026-10-03T11:00:00+08:00") + seconds * 1000).toISOString(), result = measure("live", config, state, { scaleId: "s1", bootId, sequence: sequence++, sampledAt, grossG }, sampledAt); state = result.state; events.push(...result.events); buckets = updateBuckets("live", config, result, buckets); return result; }, hold(grossG: number, count = 3) { for (let i = 0; i < count; i++) this.sample(grossG); }, reboot() { bootId = "boot2"; sequence = 0; }, overwrite(next: DeviceState) { state = next; } }; }
test("three stable readings establish an opening then confirmed take and refill", () => { const s = stream(); s.sample(1300); s.sample(1300); assert.equal(s.events.length, 0); s.sample(1300); assert.equal(s.events[0].kind, "opening"); assert.equal(s.events[0].weightG, 1000); s.hold(1200); s.hold(1250); assert.deepEqual(s.events.map(e => [e.kind, e.weightG]), [["opening", 1000], ["take", 100], ["refill", 50]]); });
test("small decreases accumulate relative to confirmed baseline instead of disappearing", () => { const s = stream(); s.hold(1300); s.hold(1299); s.hold(1298); assert.equal(s.events.filter(e => e.kind === "take").length, 0); s.hold(1297); assert.equal(s.events.find(e => e.kind === "take")?.weightG, 3); });
test("lifting and returning a bowl does not count its mass as taken", () => { const s = stream(); s.hold(1300); s.sample(0); assert.equal(s.state.mode, "removed"); s.hold(1150); assert.equal(s.events.filter(e => e.kind === "take").length, 0); assert.equal(s.events.find(e => e.kind === "pending")?.weightG, 150); assert.equal(s.state.mode, "anomaly"); });
test("returning the same bowl with equal mass creates no pending or take", () => { const s = stream(); s.hold(1000); s.sample(0); s.hold(1000); assert.equal(s.events.length, 1); assert.equal(s.state.mode, "active"); });
test("offline gaps and reboots preserve uncertain difference without invented demand", () => { for (const reboot of [false, true]) { const s = stream(); s.hold(1300); if (reboot) s.reboot(); s.sample(1200, reboot ? 1 : 12); s.hold(1200); assert.equal(s.events.filter(e => e.kind === "take").length, 0); assert.equal(s.events.find(e => e.kind === "pending")?.weightG, 100); } });
test("duplicates, sequence regressions and old boot IDs are ignored", () => { const s = stream(); s.hold(1300); const old = structuredClone(s.state); let r = measure("live", config, old, { scaleId: "s1", bootId: "boot", sequence: old.sequence, sampledAt: new Date(Date.parse(old.sampledAt) + 1000).toISOString(), grossG: 1100 }, new Date(Date.parse(old.sampledAt) + 1000).toISOString()); assert.equal(r.accepted, false); s.reboot(); s.hold(1300); r = measure("live", config, s.state, { scaleId: "s1", bootId: "boot", sequence: 999, sampledAt: new Date(Date.parse(s.state.sampledAt) + 1000).toISOString(), grossG: 1100 }, new Date(Date.parse(s.state.sampledAt) + 1000).toISOString()); assert.equal(r.accepted, false); });
test("zero food is an empty bowl; implausible jumps become pending", () => { const s = stream(); s.hold(400); s.hold(300); assert.equal(s.state.mode, "empty"); assert.equal(s.events.find(e => e.kind === "take")?.weightG, 100); const jump = stream(); jump.hold(1300); jump.hold(500); assert.equal(jump.events.filter(e => e.kind === "take").length, 0); assert.equal(jump.events.find(e => e.kind === "pending")?.weightG, 800); });
test("ordinary stabilization retains last verified weight and valid coverage", () => { const s = stream(); s.hold(1300); const result = s.sample(1250); assert.equal(s.state.displayedNet, 1000); assert.equal(result.intervals.length, 1); s.hold(1250); for (let i = 0; i < 40; i++) s.sample(1250 - Math.floor(i / 6) * 10); const rate = consumptionRate(s.buckets, 47); assert(rate.coverage > .9); assert(rate.rate !== null); });
test("missing intervals never improve rate coverage or produce an apparently mature rate", () => { const s = stream(); s.hold(1300); s.hold(1250); s.sample(1200, 120); s.hold(1200); const result = consumptionRate(s.buckets, 300); assert(result.coverage < .1); assert.equal(result.rate, null); });
test("minute intervals split at boundary and cannot exceed 60 seconds", () => { const from = Date.parse("2026-10-03T11:00:58Z"); assert.deepEqual(minuteParts(from, from + 5000).map(p => p.seconds), [2, 3]); const s = stream(); s.hold(1300); s.hold(1300, 120); assert(s.buckets.every(b => b.observedSeconds <= 60)); assert.equal(s.buckets.reduce((n, b) => n + b.observedSeconds, 0), 120); });
test("calibration reset suppresses new opening and cannot create take", () => { const s = stream(); s.hold(1300); s.overwrite({ ...s.state, stableNet: null, displayedNet: null, candidates: [], needsBaseline: true, beforeRemoval: null, suppressOpening: true }); s.hold(1200); assert.equal(s.events.length, 1); assert.equal(s.state.stableNet, 900); });
test("a new local day records verified opening once without inferring overnight consumption", () => { let state = newState(); const events: WeightEvent[] = []; const send = (at: string, seq: number, grossG: number, bootId = "carry") => { const result = measure("live", config, state, { scaleId: "s1", bootId, sequence: seq, sampledAt: at, grossG }, at); state = result.state; events.push(...result.events); }; for (let i = 0; i < 3; i++) send(`2026-10-03T23:59:5${i}+08:00`, i, 1300); for (let i = 0; i < 3; i++) send(`2026-10-04T11:00:0${i}+08:00`, i + 3, 1100); for (let i = 0; i < 3; i++) send(`2026-10-04T12:00:0${i}+08:00`, i, 1100, "new-boot"); assert.deepEqual(events.filter(e => e.kind === "opening").map(e => e.weightG), [1000, 800]); assert.equal(events.filter(e => e.kind === "take").length, 0); assert.equal(events.filter(e => e.kind === "pending").length, 0); assert.equal(state.openedDate, "2026-10-04"); });

test("one empty bowl does not imply the dish is unavailable while another bowl has food", () => { const base = {source:"live" as const, dishId:"d", minute:"2026-10-03T03:00:00.000Z", takeG:0,refillG:0,observedSeconds:60,emptySeconds:60,remainingG:0}; const start = Date.parse(base.minute), a = {...base,scaleId:"a",emptySpans:[[start,start+60000]]}, b = {...base,scaleId:"b",emptySpans:[[start+30000,start+60000]]}; assert.equal(dishEmptySeconds([a,b], ["a","b"], start,start+60000),30); assert.equal(dishEmptySeconds([a,{...b,emptySpans:[]}], ["a","b"],start,start+60000),0); });

test("equal-weight recovery still marks missing measurement interval without invented demand", () => { const s=stream();s.hold(1300);s.sample(1300,15);s.hold(1300);assert.equal(s.events.filter(e=>e.kind==="take").length,0);assert.equal(s.events.filter(e=>e.kind==="pending").length,0);assert.equal(s.events.filter(e=>e.kind==="correction"&&e.resolution==="data_gap").length,1); });

test("a normal large refill from empty to full counts supply without an anomaly", () => { const s=stream();s.hold(300);s.hold(1300);assert.equal(s.state.mode,"active");assert.equal(s.events.filter(e=>e.kind==="pending").length,0);assert.equal(s.events.find(e=>e.kind==="refill")?.weightG,1000); });

test('historical single-bowl aggregate minutes retain short stockouts without inventing multi-bowl overlap',()=>{
 const from=Date.parse('2026-09-04T11:00:00+08:00');const bucket={source:'live' as const,scaleId:'a',dishId:'beef',minute:new Date(from).toISOString(),takeG:0,refillG:100,observedSeconds:60,emptySeconds:25,remainingG:100};
 assert.equal(dishEmptySeconds([bucket],['a'],from,from+60000),25);
 assert.equal(dishEmptySeconds([bucket],['a','b'],from,from+60000),0);
});
