import { readFileSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const dir=resolve(process.argv[2]??'output/unified-36x42-20260903-20261005-v4'),read=p=>JSON.parse(readFileSync(dir+'/'+p,'utf8')),manifest=read('manifest.json'),v=read('validation.json');
const bundles=Array.from({length:manifest.expectedBatches},(_,i)=>JSON.parse(read(`batches/${String(i+1).padStart(4,'0')}.json`).payload));
const dish=manifest.catalog.map(c=>{const bs=bundles.filter(b=>b.daily.dishId===c.id),known=bs.filter(b=>b.daily.takeFinal!==null),weights=known.map(b=>b.daily.takeFinal);return {id:c.id,name:c.name,days:bs.length,complete:known.length,partial:bs.length-known.length,stockoutDays:bs.filter(b=>b.daily.supply==='stockout').length,observedTakeG:bs.reduce((a,b)=>a+b.minutes.reduce((s,m)=>s+m.takeG,0),0),meanCompleteTakeG:weights.reduce((a,x)=>a+x,0)/weights.length,minCompleteTakeG:Math.min(...weights),maxCompleteTakeG:Math.max(...weights),tableWasteG:bs.reduce((a,b)=>a+b.daily.waste,0),kitchenWasteG:bs.reduce((a,b)=>a+b.execution.closingWaste,0)};});
const quality={configuredGuestsRange:[115,170],configuredMeanIntakeRangeG:[480,780],configuredMaxTableWasteShare:.22,configuredRefillsRange:[150,280],maxSeats:20};
for(const day of v.daily){assert(day.guests>=115&&day.guests<=170);assert(day.meanIntakeG>=480&&day.meanIntakeG<=780);assert(day.tableWasteG/(day.takeG+day.tableWasteG)<=.22);assert(day.refills>=150&&day.refills<=280);assert(day.maxSeats<=20);}
assert(v.averageGuests>=130&&v.averageGuests<=142);
const previousKitchen=new Map(),sourcing=bundles.map(b=>{const x=b.execution,carriedG=previousKitchen.get(x.dishId)??0;assert(carriedG<=x.prepared);previousKitchen.set(x.dishId,x.kitchenRetained);return {date:x.date,dishId:x.dishId,carriedG,freshPreparedG:x.prepared-carriedG,preparedAvailableG:x.prepared,addedG:x.added,transferredG:b.kitchen.filter(e=>['opening','refill'].includes(e.kind)).reduce((a,e)=>a+e.weightG,0),kitchenWasteG:x.ageWaste+x.closingWaste+x.otherWaste,kitchenRetainedG:x.kitchenRetained};});
for(const x of sourcing)assert.equal(x.carriedG+x.freshPreparedG+x.addedG,x.transferredG+x.kitchenWasteG+x.kitchenRetainedG);
writeFileSync(dir+'/kitchen-sourcing.json',JSON.stringify(sourcing,null,2));
const report={kitchenCarryConservation:true,datasetId:manifest.datasetId,parameters:manifest.parameters,quality,passed:true,daily:v.daily,dishes:dish,totals:{guests:v.daily.reduce((s,d)=>s+d.guests,0),dishDays:manifest.expectedBatches,minutes:bundles.reduce((a,b)=>a+b.minutes.length,0),events:bundles.reduce((a,b)=>a+b.events.length,0),partialDishDays:dish.reduce((s,d)=>s+d.partial,0),stockoutDishDays:dish.reduce((s,d)=>s+d.stockoutDays,0),confirmedWithdrawals:bundles.reduce((a,b)=>a+b.events.filter(e=>e.kind==='pending').length,0)}};
writeFileSync(dir+'/distribution.json',JSON.stringify(report,null,2));
const cell=v=>`<td>${typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):v}</td>`,table=(headers,rows)=>`<table><thead><tr>${headers.map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(cell).join('')+'</tr>').join('')}</tbody></table>`;
writeFileSync(dir+'/report.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>36 种菜、42 个碗位模拟数据校验</title><style>body{font:14px system-ui;max-width:1200px;margin:32px auto;color:#173e32;background:#f7faf8}h1{font-size:25px}table{border-collapse:collapse;width:100%;background:white;margin:20px 0}th,td{padding:7px 10px;border-bottom:1px solid #e2e8e4;text-align:right}th:first-child,td:first-child{text-align:left}p{line-height:1.8}h2{margin-top:36px;font-size:19px}</style><h1>36 种菜、42 个碗位 · ${v.days} 天统一模拟数据</h1><p>${manifest.parameters.start}—${manifest.parameters.end}，北京时间 11:00—22:00。${report.totals.guests} 位顾客，日均 ${v.averageGuests.toFixed(1)} 人；20 个座位。所有重量由顾客与厨房事件推导。4 个菜品日包含设备缺测，缺测取用保持未知。预测由主体回放计算，模拟人工确认不代表当时实际运行过模型。</p><p>重量守恒、席位上限、顾客取用上限、事件/分钟/日统计、快照截止和文件校验均通过。实际备料表示开档可用总量，包含前日厨房保留；新增备料 = 当日可用备料 − 前日保留，各菜逐日连续守恒见 kitchen-sourcing.json。排队反映高峰拥挤；日均候位约 9—33 分钟，未假定所有顾客可以立即入座。</p><h2>逐日分布</h2>${table(['日期','顾客','周转/座','用餐分钟','候位分钟','人均取用g','补菜次数','台面报损g','厨房报损g'],v.daily.map(d=>[d.date,d.guests,d.turnover,d.meanMealMinutes,d.meanWaitMinutes,d.meanIntakeG,d.refills,d.tableWasteG,d.kitchenWasteG]))}<h2>逐菜分布</h2>${table(['菜名','完整天数','缺测天数','缺菜天数','完整日均取用g','最低g','最高g','台面报损g','厨房报损g'],dish.map(d=>[d.name,d.complete,d.partial,d.stockoutDays,d.meanCompleteTakeG,d.minCompleteTakeG,d.maxCompleteTakeG,d.tableWasteG,d.kitchenWasteG]))}<h2>异常证据</h2>${table(['日期','菜品','观测状态','缺菜分钟','撤碗报损g'],v.daily.flatMap(d=>d.anomalies.map(a=>[d.date,manifest.catalog.find(c=>c.id===a.dishId).name,a.status,a.stockoutMinutes??'未知',a.ageWaste])))}</html>`);
console.log(report.totals);
